const xmlPeerString = `
  <qdbapi>
    <record>
      <fiscal_ye_date_formatted_year>2019</fiscal_ye_date_formatted_year>
      <_01_ratio_students_enrollment>3000</_01_ratio_students_enrollment>
      <_01a_ratio_students_enrollment___change />
      <_01b_ratio_students_enrollment_average />
      <_01c_ratio_students_enrollment_peak_enrolmment>
        3899
      </_01c_ratio_students_enrollment_peak_enrolmment>
      <_02_ratio_student_faculty_ratio>0.0748</_02_ratio_student_faculty_ratio>
      <main_queryregions>SO</main_queryregions>
      <_01_yes_no_students_enrollment>Yes</_01_yes_no_students_enrollment>
      <_01c_yes_no_students_enrollment_peak_enrolmment>
        Yes
      </_01c_yes_no_students_enrollment_peak_enrolmment>
      <_02_yes_no_student_faculty_ratio>Yes</_02_yes_no_student_faculty_ratio>
      <_01_03_ft_teachers>197</_01_03_ft_teachers>
      <_01_05_pt_teachers>55</_01_05_pt_teachers>
      <_01_01_students_average_enrollment>
        3000
      </_01_01_students_average_enrollment>
      <_03_ratio_expendable_reserves___in_days>
        -7319
      </_03_ratio_expendable_reserves___in_days>
      <_03_yes_no_expendable_reserves___in_days>
        Yes
      </_03_yes_no_expendable_reserves___in_days>
      <_03_12_total_unrestricted_net_assets>
        184565.00
      </_03_12_total_unrestricted_net_assets>
      <_03_08_land__buildings_and_equipment__net>
        100000.00
      </_03_08_land__buildings_and_equipment__net>
      <_03_11_total_debt>124555.00</_03_11_total_debt>
      <_03_08_land__buildings_and_equipment__net>
        100000.00
      </_03_08_land__buildings_and_equipment__net>
      <_03_11_total_debt>124555.00</_03_11_total_debt>
      <_04_08_total_expenses>307049.00</_04_08_total_expenses>
      <_04_09_total_depreciation_expense>
        316253.00
      </_04_09_total_depreciation_expense>
      <_04_ratio_expendable_reserves______of_total_cash_expenses>
        -20.053
      </_04_ratio_expendable_reserves______of_total_cash_expenses>
      <_04_yes_no_expendable_reserves______of_total_cash_expenses>
        Yes
      </_04_yes_no_expendable_reserves______of_total_cash_expenses>
      <_05_ratio_cash_available_to_deferred_revenues>
        1.15
      </_05_ratio_cash_available_to_deferred_revenues>
      <_05_yes_no_cash_available_to_deferred_revenues>
        Yes
      </_05_yes_no_cash_available_to_deferred_revenues>
      <_03_02_total_cash>123444.00</_03_02_total_cash>
      <_03_03_non_endowment_investments>
        133909.00
      </_03_03_non_endowment_investments>
      <_03_10_deferred_revenue>119898.00</_03_10_deferred_revenue>
      <_06_ratio_liquidity_ratio>-34.06</_06_ratio_liquidity_ratio>
      <_06_yes_no_liquidity_ratio>Yes</_06_yes_no_liquidity_ratio>
      <_03_09_current_liabilities>112343.00</_03_09_current_liabilities>
      <_07a_ratio_as_per_statement_of_cash_flows>
        344962
      </_07a_ratio_as_per_statement_of_cash_flows>
      <_07a_yes_no_as_per_statement_of_cash_flows>
        Yes
      </_07a_yes_no_as_per_statement_of_cash_flows>
      <_07b_ratio_depreciation_expenses_on_3_7_year_assets>
        97655
      </_07b_ratio_depreciation_expenses_on_3_7_year_assets>
      <_07b_yes_no_depreciation_expenses_on_3_7_year_assets>
        Yes
      </_07b_yes_no_depreciation_expenses_on_3_7_year_assets>
      <_07c_ratio_over_under_benchmark>247307</_07c_ratio_over_under_benchmark>
      <_07c_yes_no_over_under_benchmark>Yes</_07c_yes_no_over_under_benchmark>
      <update_id>1701460985308</update_id>
    </record>
    <record>
      <fiscal_ye_date_formatted_year>2019</fiscal_ye_date_formatted_year>
      <_01_ratio_students_enrollment>3500</_01_ratio_students_enrollment>
      <_01a_ratio_students_enrollment___change />
      <_01b_ratio_students_enrollment_average />
      <_01c_ratio_students_enrollment_peak_enrolmment>
        4444
      </_01c_ratio_students_enrollment_peak_enrolmment>
      <_02_ratio_student_faculty_ratio>0.0636</_02_ratio_student_faculty_ratio>
      <main_queryregions>SO</main_queryregions>
      <_01_yes_no_students_enrollment>Yes</_01_yes_no_students_enrollment>
      <_01c_yes_no_students_enrollment_peak_enrolmment>
        Yes
      </_01c_yes_no_students_enrollment_peak_enrolmment>
      <_02_yes_no_student_faculty_ratio>Yes</_02_yes_no_student_faculty_ratio>
      <_01_03_ft_teachers>200</_01_03_ft_teachers>
      <_01_05_pt_teachers>45</_01_05_pt_teachers>
      <_01_01_students_average_enrollment>
        3500
      </_01_01_students_average_enrollment>
      <_03_ratio_expendable_reserves___in_days>
        -3526
      </_03_ratio_expendable_reserves___in_days>
      <_03_yes_no_expendable_reserves___in_days>
        Yes
      </_03_yes_no_expendable_reserves___in_days>
      <_03_12_total_unrestricted_net_assets>
        120323.00
      </_03_12_total_unrestricted_net_assets>
      <_03_08_land__buildings_and_equipment__net>
        80000.00
      </_03_08_land__buildings_and_equipment__net>
      <_03_11_total_debt>112343.00</_03_11_total_debt>
      <_03_08_land__buildings_and_equipment__net>
        80000.00
      </_03_08_land__buildings_and_equipment__net>
      <_03_11_total_debt>112343.00</_03_11_total_debt>
      <_04_08_total_expenses>118997.00</_04_08_total_expenses>
      <_04_09_total_depreciation_expense>
        131452.00
      </_04_09_total_depreciation_expense>
      <_04_ratio_expendable_reserves______of_total_cash_expenses>
        -9.661
      </_04_ratio_expendable_reserves______of_total_cash_expenses>
      <_04_yes_no_expendable_reserves______of_total_cash_expenses>
        Yes
      </_04_yes_no_expendable_reserves______of_total_cash_expenses>
      <_05_ratio_cash_available_to_deferred_revenues>
        1.13
      </_05_ratio_cash_available_to_deferred_revenues>
      <_05_yes_no_cash_available_to_deferred_revenues>
        Yes
      </_05_yes_no_cash_available_to_deferred_revenues>
      <_03_02_total_cash>104445.00</_03_02_total_cash>
      <_03_03_non_endowment_investments>
        113989.00
      </_03_03_non_endowment_investments>
      <_03_10_deferred_revenue>102343.00</_03_10_deferred_revenue>
      <_06_ratio_liquidity_ratio>-21.84</_06_ratio_liquidity_ratio>
      <_06_yes_no_liquidity_ratio>Yes</_06_yes_no_liquidity_ratio>
      <_03_09_current_liabilities>92343.00</_03_09_current_liabilities>
      <_07a_ratio_as_per_statement_of_cash_flows>
        170405
      </_07a_ratio_as_per_statement_of_cash_flows>
      <_07a_yes_no_as_per_statement_of_cash_flows>
        Yes
      </_07a_yes_no_as_per_statement_of_cash_flows>
      <_07b_ratio_depreciation_expenses_on_3_7_year_assets>
        82333
      </_07b_ratio_depreciation_expenses_on_3_7_year_assets>
      <_07b_yes_no_depreciation_expenses_on_3_7_year_assets>
        Yes
      </_07b_yes_no_depreciation_expenses_on_3_7_year_assets>
      <_07c_ratio_over_under_benchmark>88072</_07c_ratio_over_under_benchmark>
      <_07c_yes_no_over_under_benchmark>Yes</_07c_yes_no_over_under_benchmark>
      <update_id>1701460985308</update_id>
    </record>
    <record>
      <fiscal_ye_date_formatted_year>2019</fiscal_ye_date_formatted_year>
      <_01_ratio_students_enrollment>2000</_01_ratio_students_enrollment>
      <_01a_ratio_students_enrollment___change />
      <_01b_ratio_students_enrollment_average />
      <_01c_ratio_students_enrollment_peak_enrolmment>
        7000
      </_01c_ratio_students_enrollment_peak_enrolmment>
      <_02_ratio_student_faculty_ratio>5.5520</_02_ratio_student_faculty_ratio>
      <main_queryregions>PL</main_queryregions>
      <_01_yes_no_students_enrollment>Yes</_01_yes_no_students_enrollment>
      <_01c_yes_no_students_enrollment_peak_enrolmment>
        Yes
      </_01c_yes_no_students_enrollment_peak_enrolmment>
      <_02_yes_no_student_faculty_ratio>Yes</_02_yes_no_student_faculty_ratio>
      <_01_03_ft_teachers>104</_01_03_ft_teachers>
      <_01_05_pt_teachers>22000</_01_05_pt_teachers>
      <_01_01_students_average_enrollment>
        2000
      </_01_01_students_average_enrollment>
      <_03_ratio_expendable_reserves___in_days>
        -9271
      </_03_ratio_expendable_reserves___in_days>
      <_03_yes_no_expendable_reserves___in_days>
        Yes
      </_03_yes_no_expendable_reserves___in_days>
      <_03_12_total_unrestricted_net_assets>
        127000.00
      </_03_12_total_unrestricted_net_assets>
      <_03_08_land__buildings_and_equipment__net>
        102000.00
      </_03_08_land__buildings_and_equipment__net>
      <_03_11_total_debt>122000.00</_03_11_total_debt>
      <_03_08_land__buildings_and_equipment__net>
        102000.00
      </_03_08_land__buildings_and_equipment__net>
      <_03_11_total_debt>122000.00</_03_11_total_debt>
      <_04_08_total_expenses>177000.00</_04_08_total_expenses>
      <_04_09_total_depreciation_expense>
        182000.00
      </_04_09_total_depreciation_expense>
      <_04_ratio_expendable_reserves______of_total_cash_expenses>
        -25.400
      </_04_ratio_expendable_reserves______of_total_cash_expenses>
      <_04_yes_no_expendable_reserves______of_total_cash_expenses>
        Yes
      </_04_yes_no_expendable_reserves______of_total_cash_expenses>
      <_05_ratio_cash_available_to_deferred_revenues>
        0.36
      </_05_ratio_cash_available_to_deferred_revenues>
      <_05_yes_no_cash_available_to_deferred_revenues>
        Yes
      </_05_yes_no_cash_available_to_deferred_revenues>
      <_03_02_total_cash>77000.00</_03_02_total_cash>
      <_03_03_non_endowment_investments>
        82000.00
      </_03_03_non_endowment_investments>
      <_03_10_deferred_revenue>117000.00</_03_10_deferred_revenue>
      <_06_ratio_liquidity_ratio>-31.80</_06_ratio_liquidity_ratio>
      <_06_yes_no_liquidity_ratio>Yes</_06_yes_no_liquidity_ratio>
      <_03_09_current_liabilities>112000.00</_03_09_current_liabilities>
      <_07a_ratio_as_per_statement_of_cash_flows>
        207000
      </_07a_ratio_as_per_statement_of_cash_flows>
      <_07a_yes_no_as_per_statement_of_cash_flows>
        Yes
      </_07a_yes_no_as_per_statement_of_cash_flows>
      <_07b_ratio_depreciation_expenses_on_3_7_year_assets>
        67000
      </_07b_ratio_depreciation_expenses_on_3_7_year_assets>
      <_07b_yes_no_depreciation_expenses_on_3_7_year_assets>
        Yes
      </_07b_yes_no_depreciation_expenses_on_3_7_year_assets>
      <_07c_ratio_over_under_benchmark>140000</_07c_ratio_over_under_benchmark>
      <_07c_yes_no_over_under_benchmark>Yes</_07c_yes_no_over_under_benchmark>
      <update_id>1701360570736</update_id>
    </record>
    <record>
      <fiscal_ye_date_formatted_year>2020</fiscal_ye_date_formatted_year>
      <_01_ratio_students_enrollment>10000</_01_ratio_students_enrollment>
      <_01a_ratio_students_enrollment___change>
        4.000
      </_01a_ratio_students_enrollment___change>
      <_01b_ratio_students_enrollment_average>
        6000
      </_01b_ratio_students_enrollment_average>
      <_01c_ratio_students_enrollment_peak_enrolmment>
        11455
      </_01c_ratio_students_enrollment_peak_enrolmment>
      <_02_ratio_student_faculty_ratio>0.0600</_02_ratio_student_faculty_ratio>
      <main_queryregions>NE</main_queryregions>
      <_01_yes_no_students_enrollment>Yes</_01_yes_no_students_enrollment>
      <_01c_yes_no_students_enrollment_peak_enrolmment>
        Yes
      </_01c_yes_no_students_enrollment_peak_enrolmment>
      <_02_yes_no_student_faculty_ratio>Yes</_02_yes_no_student_faculty_ratio>
      <_01_03_ft_teachers>500</_01_03_ft_teachers>
      <_01_05_pt_teachers>200</_01_05_pt_teachers>
      <_01_01_students_average_enrollment>
        10000
      </_01_01_students_average_enrollment>
      <_03_ratio_expendable_reserves___in_days>
        -6897
      </_03_ratio_expendable_reserves___in_days>
      <_03_yes_no_expendable_reserves___in_days>
        Yes
      </_03_yes_no_expendable_reserves___in_days>
      <_03_12_total_unrestricted_net_assets>
        201323.00
      </_03_12_total_unrestricted_net_assets>
      <_03_08_land__buildings_and_equipment__net>
        125000.00
      </_03_08_land__buildings_and_equipment__net>
      <_03_11_total_debt>190232.00</_03_11_total_debt>
      <_03_08_land__buildings_and_equipment__net>
        125000.00
      </_03_08_land__buildings_and_equipment__net>
      <_03_11_total_debt>190232.00</_03_11_total_debt>
      <_04_08_total_expenses>309986.00</_04_08_total_expenses>
      <_04_09_total_depreciation_expense>
        320640.00
      </_04_09_total_depreciation_expense>
      <_04_ratio_expendable_reserves______of_total_cash_expenses>
        -18.896
      </_04_ratio_expendable_reserves______of_total_cash_expenses>
      <_04_yes_no_expendable_reserves______of_total_cash_expenses>
        Yes
      </_04_yes_no_expendable_reserves______of_total_cash_expenses>
      <_05_ratio_cash_available_to_deferred_revenues>
        0.32
      </_05_ratio_cash_available_to_deferred_revenues>
      <_05_yes_no_cash_available_to_deferred_revenues>
        Yes
      </_05_yes_no_cash_available_to_deferred_revenues>
      <_03_02_total_cash>120322.00</_03_02_total_cash>
      <_03_03_non_endowment_investments>
        129878.00
      </_03_03_non_endowment_investments>
      <_03_10_deferred_revenue>189565.00</_03_10_deferred_revenue>
      <_06_ratio_liquidity_ratio>-10.57</_06_ratio_liquidity_ratio>
      <_06_yes_no_liquidity_ratio>Yes</_06_yes_no_liquidity_ratio>
      <_03_09_current_liabilities>165898.00</_03_09_current_liabilities>
      <_07a_ratio_as_per_statement_of_cash_flows>
        391758
      </_07a_ratio_as_per_statement_of_cash_flows>
      <_07a_yes_no_as_per_statement_of_cash_flows>
        Yes
      </_07a_yes_no_as_per_statement_of_cash_flows>
      <_07b_ratio_depreciation_expenses_on_3_7_year_assets>
        105433
      </_07b_ratio_depreciation_expenses_on_3_7_year_assets>
      <_07b_yes_no_depreciation_expenses_on_3_7_year_assets>
        Yes
      </_07b_yes_no_depreciation_expenses_on_3_7_year_assets>
      <_07c_ratio_over_under_benchmark>286325</_07c_ratio_over_under_benchmark>
      <_07c_yes_no_over_under_benchmark>Yes</_07c_yes_no_over_under_benchmark>
      <update_id>1701460985308</update_id>
    </record>
    <record>
      <fiscal_ye_date_formatted_year>2020</fiscal_ye_date_formatted_year>
      <_01_ratio_students_enrollment>9000</_01_ratio_students_enrollment>
      <_01a_ratio_students_enrollment___change>
        3.500
      </_01a_ratio_students_enrollment___change>
      <_01b_ratio_students_enrollment_average>
        5500
      </_01b_ratio_students_enrollment_average>
      <_01c_ratio_students_enrollment_peak_enrolmment>
        19000
      </_01c_ratio_students_enrollment_peak_enrolmment>
      <_02_ratio_student_faculty_ratio>5.9444</_02_ratio_student_faculty_ratio>
      <main_queryregions>PL</main_queryregions>
      <_01_yes_no_students_enrollment>Yes</_01_yes_no_students_enrollment>
      <_01c_yes_no_students_enrollment_peak_enrolmment>
        Yes
      </_01c_yes_no_students_enrollment_peak_enrolmment>
      <_02_yes_no_student_faculty_ratio>Yes</_02_yes_no_student_faculty_ratio>
      <_01_03_ft_teachers>29000</_01_03_ft_teachers>
      <_01_05_pt_teachers>49000</_01_05_pt_teachers>
      <_01_01_students_average_enrollment>
        9000
      </_01_01_students_average_enrollment>
      <_03_ratio_expendable_reserves___in_days>
        -9454
      </_03_ratio_expendable_reserves___in_days>
      <_03_yes_no_expendable_reserves___in_days>
        Yes
      </_03_yes_no_expendable_reserves___in_days>
      <_03_12_total_unrestricted_net_assets>
        259000.00
      </_03_12_total_unrestricted_net_assets>
      <_03_08_land__buildings_and_equipment__net>
        219000.00
      </_03_08_land__buildings_and_equipment__net>
      <_03_11_total_debt>249000.00</_03_11_total_debt>
      <_03_08_land__buildings_and_equipment__net>
        219000.00
      </_03_08_land__buildings_and_equipment__net>
      <_03_11_total_debt>249000.00</_03_11_total_debt>
      <_04_08_total_expenses>359000.00</_04_08_total_expenses>
      <_04_09_total_depreciation_expense>
        369000.00
      </_04_09_total_depreciation_expense>
      <_04_ratio_expendable_reserves______of_total_cash_expenses>
        -25.900
      </_04_ratio_expendable_reserves______of_total_cash_expenses>
      <_04_yes_no_expendable_reserves______of_total_cash_expenses>
        Yes
      </_04_yes_no_expendable_reserves______of_total_cash_expenses>
      <_05_ratio_cash_available_to_deferred_revenues>
        0.37
      </_05_ratio_cash_available_to_deferred_revenues>
      <_05_yes_no_cash_available_to_deferred_revenues>
        Yes
      </_05_yes_no_cash_available_to_deferred_revenues>
      <_03_02_total_cash>159000.00</_03_02_total_cash>
      <_03_03_non_endowment_investments>
        169000.00
      </_03_03_non_endowment_investments>
      <_03_10_deferred_revenue>239000.00</_03_10_deferred_revenue>
      <_06_ratio_liquidity_ratio>-32.80</_06_ratio_liquidity_ratio>
      <_06_yes_no_liquidity_ratio>Yes</_06_yes_no_liquidity_ratio>
      <_03_09_current_liabilities>229000.00</_03_09_current_liabilities>
      <_07a_ratio_as_per_statement_of_cash_flows>
        419000
      </_07a_ratio_as_per_statement_of_cash_flows>
      <_07a_yes_no_as_per_statement_of_cash_flows>
        Yes
      </_07a_yes_no_as_per_statement_of_cash_flows>
      <_07b_ratio_depreciation_expenses_on_3_7_year_assets>
        139000
      </_07b_ratio_depreciation_expenses_on_3_7_year_assets>
      <_07b_yes_no_depreciation_expenses_on_3_7_year_assets>
        Yes
      </_07b_yes_no_depreciation_expenses_on_3_7_year_assets>
      <_07c_ratio_over_under_benchmark>280000</_07c_ratio_over_under_benchmark>
      <_07c_yes_no_over_under_benchmark>Yes</_07c_yes_no_over_under_benchmark>
      <update_id>1698859871348</update_id>
    </record>
    <record>
      <fiscal_ye_date_formatted_year>2021</fiscal_ye_date_formatted_year>
      <_01_ratio_students_enrollment>9101</_01_ratio_students_enrollment>
      <_01a_ratio_students_enrollment___change>
        0.011
      </_01a_ratio_students_enrollment___change>
      <_01b_ratio_students_enrollment_average>
        9051
      </_01b_ratio_students_enrollment_average>
      <_01c_ratio_students_enrollment_peak_enrolmment>
        10434
      </_01c_ratio_students_enrollment_peak_enrolmment>
      <_02_ratio_student_faculty_ratio>0.0555</_02_ratio_student_faculty_ratio>
      <main_queryregions>SO</main_queryregions>
      <_01_yes_no_students_enrollment>Yes</_01_yes_no_students_enrollment>
      <_01c_yes_no_students_enrollment_peak_enrolmment>
        Yes
      </_01c_yes_no_students_enrollment_peak_enrolmment>
      <_02_yes_no_student_faculty_ratio>Yes</_02_yes_no_student_faculty_ratio>
      <_01_03_ft_teachers>453</_01_03_ft_teachers>
      <_01_05_pt_teachers>104</_01_05_pt_teachers>
      <_01_01_students_average_enrollment>
        9101
      </_01_01_students_average_enrollment>
      <_03_ratio_expendable_reserves___in_days>
        -5713
      </_03_ratio_expendable_reserves___in_days>
      <_03_yes_no_expendable_reserves___in_days>
        Yes
      </_03_yes_no_expendable_reserves___in_days>
      <_03_12_total_unrestricted_net_assets>
        201900.00
      </_03_12_total_unrestricted_net_assets>
      <_03_08_land__buildings_and_equipment__net>
        120000.00
      </_03_08_land__buildings_and_equipment__net>
      <_03_11_total_debt>191898.00</_03_11_total_debt>
      <_03_08_land__buildings_and_equipment__net>
        120000.00
      </_03_08_land__buildings_and_equipment__net>
      <_03_11_total_debt>191898.00</_03_11_total_debt>
      <_04_08_total_expenses>321882.00</_04_08_total_expenses>
      <_04_09_total_depreciation_expense>
        334782.00
      </_04_09_total_depreciation_expense>
      <_04_ratio_expendable_reserves______of_total_cash_expenses>
        -15.651
      </_04_ratio_expendable_reserves______of_total_cash_expenses>
      <_04_yes_no_expendable_reserves______of_total_cash_expenses>
        Yes
      </_04_yes_no_expendable_reserves______of_total_cash_expenses>
      <_05_ratio_cash_available_to_deferred_revenues>
        0.32
      </_05_ratio_cash_available_to_deferred_revenues>
      <_05_yes_no_cash_available_to_deferred_revenues>
        Yes
      </_05_yes_no_cash_available_to_deferred_revenues>
      <_03_02_total_cash>120344.00</_03_02_total_cash>
      <_03_03_non_endowment_investments>
        128999.00
      </_03_03_non_endowment_investments>
      <_03_10_deferred_revenue>188575.00</_03_10_deferred_revenue>
      <_06_ratio_liquidity_ratio>-7.65</_06_ratio_liquidity_ratio>
      <_06_yes_no_liquidity_ratio>Yes</_06_yes_no_liquidity_ratio>
      <_03_09_current_liabilities>155999.00</_03_09_current_liabilities>
      <_07a_ratio_as_per_statement_of_cash_flows>
        396562
      </_07a_ratio_as_per_statement_of_cash_flows>
      <_07a_yes_no_as_per_statement_of_cash_flows>
        Yes
      </_07a_yes_no_as_per_statement_of_cash_flows>
      <_07b_ratio_depreciation_expenses_on_3_7_year_assets>
        104433
      </_07b_ratio_depreciation_expenses_on_3_7_year_assets>
      <_07b_yes_no_depreciation_expenses_on_3_7_year_assets>
        Yes
      </_07b_yes_no_depreciation_expenses_on_3_7_year_assets>
      <_07c_ratio_over_under_benchmark>292129</_07c_ratio_over_under_benchmark>
      <_07c_yes_no_over_under_benchmark>Yes</_07c_yes_no_over_under_benchmark>
      <update_id>1701460985308</update_id>
    </record>
    <record>
      <fiscal_ye_date_formatted_year>2021</fiscal_ye_date_formatted_year>
      <_01_ratio_students_enrollment>8404</_01_ratio_students_enrollment>
      <_01a_ratio_students_enrollment___change>
        -0.066
      </_01a_ratio_students_enrollment___change>
      <_01b_ratio_students_enrollment_average>
        8702
      </_01b_ratio_students_enrollment_average>
      <_01c_ratio_students_enrollment_peak_enrolmment>
        9007
      </_01c_ratio_students_enrollment_peak_enrolmment>
      <_02_ratio_student_faculty_ratio>0.0538</_02_ratio_student_faculty_ratio>
      <main_queryregions>SO</main_queryregions>
      <_01_yes_no_students_enrollment>Yes</_01_yes_no_students_enrollment>
      <_01c_yes_no_students_enrollment_peak_enrolmment>
        Yes
      </_01c_yes_no_students_enrollment_peak_enrolmment>
      <_02_yes_no_student_faculty_ratio>Yes</_02_yes_no_student_faculty_ratio>
      <_01_03_ft_teachers>404</_01_03_ft_teachers>
      <_01_05_pt_teachers>97</_01_05_pt_teachers>
      <_01_01_students_average_enrollment>
        8404
      </_01_01_students_average_enrollment>
      <_03_ratio_expendable_reserves___in_days>
        -9205
      </_03_ratio_expendable_reserves___in_days>
      <_03_yes_no_expendable_reserves___in_days>
        Yes
      </_03_yes_no_expendable_reserves___in_days>
      <_03_12_total_unrestricted_net_assets>
        201999.00
      </_03_12_total_unrestricted_net_assets>
      <_03_08_land__buildings_and_equipment__net>
        169185.64
      </_03_08_land__buildings_and_equipment__net>
      <_03_11_total_debt>193232.00</_03_11_total_debt>
      <_03_08_land__buildings_and_equipment__net>
        169185.64
      </_03_08_land__buildings_and_equipment__net>
      <_03_11_total_debt>193232.00</_03_11_total_debt>
      <_04_08_total_expenses>331101.00</_04_08_total_expenses>
      <_04_09_total_depreciation_expense>
        339111.00
      </_04_09_total_depreciation_expense>
      <_04_ratio_expendable_reserves______of_total_cash_expenses>
        -25.218
      </_04_ratio_expendable_reserves______of_total_cash_expenses>
      <_04_yes_no_expendable_reserves______of_total_cash_expenses>
        Yes
      </_04_yes_no_expendable_reserves______of_total_cash_expenses>
      <_05_ratio_cash_available_to_deferred_revenues>
        0.31
      </_05_ratio_cash_available_to_deferred_revenues>
      <_05_yes_no_cash_available_to_deferred_revenues>
        Yes
      </_05_yes_no_cash_available_to_deferred_revenues>
      <_03_02_total_cash>120366.00</_03_02_total_cash>
      <_03_03_non_endowment_investments>
        124555.00
      </_03_03_non_endowment_investments>
      <_03_10_deferred_revenue>187121.00</_03_10_deferred_revenue>
      <_06_ratio_liquidity_ratio>-30.16</_06_ratio_liquidity_ratio>
      <_06_yes_no_liquidity_ratio>Yes</_06_yes_no_liquidity_ratio>
      <_03_09_current_liabilities>178999.00</_03_09_current_liabilities>
      <_07a_ratio_as_per_statement_of_cash_flows>
        385371
      </_07a_ratio_as_per_statement_of_cash_flows>
      <_07a_yes_no_as_per_statement_of_cash_flows>
        Yes
      </_07a_yes_no_as_per_statement_of_cash_flows>
      <_07b_ratio_depreciation_expenses_on_3_7_year_assets>
        103233
      </_07b_ratio_depreciation_expenses_on_3_7_year_assets>
      <_07b_yes_no_depreciation_expenses_on_3_7_year_assets>
        Yes
      </_07b_yes_no_depreciation_expenses_on_3_7_year_assets>
      <_07c_ratio_over_under_benchmark>282138</_07c_ratio_over_under_benchmark>
      <_07c_yes_no_over_under_benchmark>Yes</_07c_yes_no_over_under_benchmark>
      <update_id>1701460985308</update_id>
    </record>
    <record>
      <fiscal_ye_date_formatted_year>2021</fiscal_ye_date_formatted_year>
      <_01_ratio_students_enrollment>8462</_01_ratio_students_enrollment>
      <_01a_ratio_students_enrollment___change>
        -0.060
      </_01a_ratio_students_enrollment___change>
      <_01b_ratio_students_enrollment_average>
        8731
      </_01b_ratio_students_enrollment_average>
      <_01c_ratio_students_enrollment_peak_enrolmment>
        20000
      </_01c_ratio_students_enrollment_peak_enrolmment>
      <_02_ratio_student_faculty_ratio>6.9545</_02_ratio_student_faculty_ratio>
      <main_queryregions>PL</main_queryregions>
      <_01_yes_no_students_enrollment>Yes</_01_yes_no_students_enrollment>
      <_01c_yes_no_students_enrollment_peak_enrolmment>
        Yes
      </_01c_yes_no_students_enrollment_peak_enrolmment>
      <_02_yes_no_student_faculty_ratio>Yes</_02_yes_no_student_faculty_ratio>
      <_01_03_ft_teachers>31538.461538462</_01_03_ft_teachers>
      <_01_05_pt_teachers>54615.384615385</_01_05_pt_teachers>
      <_01_01_students_average_enrollment>
        8462
      </_01_01_students_average_enrollment>
      <_03_ratio_expendable_reserves___in_days>
        -9393
      </_03_ratio_expendable_reserves___in_days>
      <_03_yes_no_expendable_reserves___in_days>
        Yes
      </_03_yes_no_expendable_reserves___in_days>
      <_03_12_total_unrestricted_net_assets>
        296923.08
      </_03_12_total_unrestricted_net_assets>
      <_03_08_land__buildings_and_equipment__net>
        250769.23
      </_03_08_land__buildings_and_equipment__net>
      <_03_11_total_debt>285384.62</_03_11_total_debt>
      <_03_08_land__buildings_and_equipment__net>
        250769.23
      </_03_08_land__buildings_and_equipment__net>
      <_03_11_total_debt>285384.62</_03_11_total_debt>
      <_04_08_total_expenses>412307.69</_04_08_total_expenses>
      <_04_09_total_depreciation_expense>
        423846.15
      </_04_09_total_depreciation_expense>
      <_04_ratio_expendable_reserves______of_total_cash_expenses>
        -25.733
      </_04_ratio_expendable_reserves______of_total_cash_expenses>
      <_04_yes_no_expendable_reserves______of_total_cash_expenses>
        Yes
      </_04_yes_no_expendable_reserves______of_total_cash_expenses>
      <_05_ratio_cash_available_to_deferred_revenues>
        0.37
      </_05_ratio_cash_available_to_deferred_revenues>
      <_05_yes_no_cash_available_to_deferred_revenues>
        Yes
      </_05_yes_no_cash_available_to_deferred_revenues>
      <_03_02_total_cash>181538.46</_03_02_total_cash>
      <_03_03_non_endowment_investments>
        193076.92
      </_03_03_non_endowment_investments>
      <_03_10_deferred_revenue>273846.15</_03_10_deferred_revenue>
      <_06_ratio_liquidity_ratio>-32.47</_06_ratio_liquidity_ratio>
      <_06_yes_no_liquidity_ratio>Yes</_06_yes_no_liquidity_ratio>
      <_03_09_current_liabilities>262307.69</_03_09_current_liabilities>
      <_07a_ratio_as_per_statement_of_cash_flows>
        481538
      </_07a_ratio_as_per_statement_of_cash_flows>
      <_07a_yes_no_as_per_statement_of_cash_flows>
        Yes
      </_07a_yes_no_as_per_statement_of_cash_flows>
      <_07b_ratio_depreciation_expenses_on_3_7_year_assets>
        158462
      </_07b_ratio_depreciation_expenses_on_3_7_year_assets>
      <_07b_yes_no_depreciation_expenses_on_3_7_year_assets>
        Yes
      </_07b_yes_no_depreciation_expenses_on_3_7_year_assets>
      <_07c_ratio_over_under_benchmark>323077</_07c_ratio_over_under_benchmark>
      <_07c_yes_no_over_under_benchmark>Yes</_07c_yes_no_over_under_benchmark>
      <update_id>1698859871348</update_id>
    </record>
    <record>
      <fiscal_ye_date_formatted_year>2022</fiscal_ye_date_formatted_year>
      <_01_ratio_students_enrollment>7550</_01_ratio_students_enrollment>
      <_01a_ratio_students_enrollment___change>
        -0.108
      </_01a_ratio_students_enrollment___change>
      <_01b_ratio_students_enrollment_average>
        8006
      </_01b_ratio_students_enrollment_average>
      <_01c_ratio_students_enrollment_peak_enrolmment>
        8500
      </_01c_ratio_students_enrollment_peak_enrolmment>
      <_02_ratio_student_faculty_ratio>0.0501</_02_ratio_student_faculty_ratio>
      <main_queryregions>SO</main_queryregions>
      <_01_yes_no_students_enrollment>Yes</_01_yes_no_students_enrollment>
      <_01c_yes_no_students_enrollment_peak_enrolmment>
        Yes
      </_01c_yes_no_students_enrollment_peak_enrolmment>
      <_02_yes_no_student_faculty_ratio>Yes</_02_yes_no_student_faculty_ratio>
      <_01_03_ft_teachers>328</_01_03_ft_teachers>
      <_01_05_pt_teachers>101</_01_05_pt_teachers>
      <_01_01_students_average_enrollment>
        7550
      </_01_01_students_average_enrollment>
      <_03_ratio_expendable_reserves___in_days>
        -4280
      </_03_ratio_expendable_reserves___in_days>
      <_03_yes_no_expendable_reserves___in_days>
        Yes
      </_03_yes_no_expendable_reserves___in_days>
      <_03_12_total_unrestricted_net_assets>
        199888.00
      </_03_12_total_unrestricted_net_assets>
      <_03_08_land__buildings_and_equipment__net>
        159888.00
      </_03_08_land__buildings_and_equipment__net>
      <_03_11_total_debt>194544.00</_03_11_total_debt>
      <_03_08_land__buildings_and_equipment__net>
        159888.00
      </_03_08_land__buildings_and_equipment__net>
      <_03_11_total_debt>194544.00</_03_11_total_debt>
      <_04_08_total_expenses>313478.00</_04_08_total_expenses>
      <_04_09_total_depreciation_expense>
        330526.00
      </_04_09_total_depreciation_expense>
      <_04_ratio_expendable_reserves______of_total_cash_expenses>
        -11.725
      </_04_ratio_expendable_reserves______of_total_cash_expenses>
      <_04_yes_no_expendable_reserves______of_total_cash_expenses>
        Yes
      </_04_yes_no_expendable_reserves______of_total_cash_expenses>
      <_05_ratio_cash_available_to_deferred_revenues>
        0.21
      </_05_ratio_cash_available_to_deferred_revenues>
      <_05_yes_no_cash_available_to_deferred_revenues>
        Yes
      </_05_yes_no_cash_available_to_deferred_revenues>
      <_03_02_total_cash>110555.00</_03_02_total_cash>
      <_03_03_non_endowment_investments>
        120444.00
      </_03_03_non_endowment_investments>
      <_03_10_deferred_revenue>190828.00</_03_10_deferred_revenue>
      <_06_ratio_liquidity_ratio>-135.32</_06_ratio_liquidity_ratio>
      <_06_yes_no_liquidity_ratio>Yes</_06_yes_no_liquidity_ratio>
      <_03_09_current_liabilities>189121.00</_03_09_current_liabilities>
      <_07a_ratio_as_per_statement_of_cash_flows>
        388319
      </_07a_ratio_as_per_statement_of_cash_flows>
      <_07a_yes_no_as_per_statement_of_cash_flows>
        Yes
      </_07a_yes_no_as_per_statement_of_cash_flows>
      <_07b_ratio_depreciation_expenses_on_3_7_year_assets>
        104555
      </_07b_ratio_depreciation_expenses_on_3_7_year_assets>
      <_07b_yes_no_depreciation_expenses_on_3_7_year_assets>
        Yes
      </_07b_yes_no_depreciation_expenses_on_3_7_year_assets>
      <_07c_ratio_over_under_benchmark>283764</_07c_ratio_over_under_benchmark>
      <_07c_yes_no_over_under_benchmark>Yes</_07c_yes_no_over_under_benchmark>
      <update_id>1701460985308</update_id>
    </record>
    <record>
      <fiscal_ye_date_formatted_year>2022</fiscal_ye_date_formatted_year>
      <_01_ratio_students_enrollment>7440</_01_ratio_students_enrollment>
      <_01a_ratio_students_enrollment___change>
        -0.121
      </_01a_ratio_students_enrollment___change>
      <_01b_ratio_students_enrollment_average>
        7951
      </_01b_ratio_students_enrollment_average>
      <_01c_ratio_students_enrollment_peak_enrolmment>
        84433
      </_01c_ratio_students_enrollment_peak_enrolmment>
      <_02_ratio_student_faculty_ratio>0.0476</_02_ratio_student_faculty_ratio>
      <main_queryregions>SO</main_queryregions>
      <_01_yes_no_students_enrollment>Yes</_01_yes_no_students_enrollment>
      <_01c_yes_no_students_enrollment_peak_enrolmment>
        Yes
      </_01c_yes_no_students_enrollment_peak_enrolmment>
      <_02_yes_no_student_faculty_ratio>Yes</_02_yes_no_student_faculty_ratio>
      <_01_03_ft_teachers>304</_01_03_ft_teachers>
      <_01_05_pt_teachers>101</_01_05_pt_teachers>
      <_01_01_students_average_enrollment>
        7440
      </_01_01_students_average_enrollment>
      <_03_ratio_expendable_reserves___in_days>
        -7418
      </_03_ratio_expendable_reserves___in_days>
      <_03_yes_no_expendable_reserves___in_days>
        Yes
      </_03_yes_no_expendable_reserves___in_days>
      <_03_12_total_unrestricted_net_assets>
        199121.00
      </_03_12_total_unrestricted_net_assets>
      <_03_08_land__buildings_and_equipment__net>
        160898.00
      </_03_08_land__buildings_and_equipment__net>
      <_03_11_total_debt>192322.00</_03_11_total_debt>
      <_03_08_land__buildings_and_equipment__net>
        160898.00
      </_03_08_land__buildings_and_equipment__net>
      <_03_11_total_debt>192322.00</_03_11_total_debt>
      <_04_08_total_expenses>342039.00</_04_08_total_expenses>
      <_04_09_total_depreciation_expense>
        351837.00
      </_04_09_total_depreciation_expense>
      <_04_ratio_expendable_reserves______of_total_cash_expenses>
        -20.323
      </_04_ratio_expendable_reserves______of_total_cash_expenses>
      <_04_yes_no_expendable_reserves______of_total_cash_expenses>
        Yes
      </_04_yes_no_expendable_reserves______of_total_cash_expenses>
      <_05_ratio_cash_available_to_deferred_revenues>
        0.26
      </_05_ratio_cash_available_to_deferred_revenues>
      <_05_yes_no_cash_available_to_deferred_revenues>
        Yes
      </_05_yes_no_cash_available_to_deferred_revenues>
      <_03_02_total_cash>120303.00</_03_02_total_cash>
      <_03_03_non_endowment_investments>
        121222.00
      </_03_03_non_endowment_investments>
      <_03_10_deferred_revenue>191343.00</_03_10_deferred_revenue>
      <_06_ratio_liquidity_ratio>-41.44</_06_ratio_liquidity_ratio>
      <_06_yes_no_liquidity_ratio>Yes</_06_yes_no_liquidity_ratio>
      <_03_09_current_liabilities>185515.00</_03_09_current_liabilities>
      <_07a_ratio_as_per_statement_of_cash_flows>
        365301
      </_07a_ratio_as_per_statement_of_cash_flows>
      <_07a_yes_no_as_per_statement_of_cash_flows>
        Yes
      </_07a_yes_no_as_per_statement_of_cash_flows>
      <_07b_ratio_depreciation_expenses_on_3_7_year_assets>
        105434
      </_07b_ratio_depreciation_expenses_on_3_7_year_assets>
      <_07b_yes_no_depreciation_expenses_on_3_7_year_assets>
        Yes
      </_07b_yes_no_depreciation_expenses_on_3_7_year_assets>
      <_07c_ratio_over_under_benchmark>259867</_07c_ratio_over_under_benchmark>
      <_07c_yes_no_over_under_benchmark>Yes</_07c_yes_no_over_under_benchmark>
      <update_id>1701460985308</update_id>
    </record>
    <record>
      <fiscal_ye_date_formatted_year>2023</fiscal_ye_date_formatted_year>
      <_01_ratio_students_enrollment>6500</_01_ratio_students_enrollment>
      <_01a_ratio_students_enrollment___change>
        0.002
      </_01a_ratio_students_enrollment___change>
      <_01b_ratio_students_enrollment_average>
        6494
      </_01b_ratio_students_enrollment_average>
      <_01c_ratio_students_enrollment_peak_enrolmment>
        8203
      </_01c_ratio_students_enrollment_peak_enrolmment>
      <_02_ratio_student_faculty_ratio>0.0615</_02_ratio_student_faculty_ratio>
      <main_queryregions>SO</main_queryregions>
      <_01_yes_no_students_enrollment>Yes</_01_yes_no_students_enrollment>
      <_01c_yes_no_students_enrollment_peak_enrolmment>
        Yes
      </_01c_yes_no_students_enrollment_peak_enrolmment>
      <_02_yes_no_student_faculty_ratio>Yes</_02_yes_no_student_faculty_ratio>
      <_01_03_ft_teachers>356</_01_03_ft_teachers>
      <_01_05_pt_teachers>88</_01_05_pt_teachers>
      <_01_01_students_average_enrollment>
        6500
      </_01_01_students_average_enrollment>
      <_03_ratio_expendable_reserves___in_days>
        -5122
      </_03_ratio_expendable_reserves___in_days>
      <_03_yes_no_expendable_reserves___in_days>
        Yes
      </_03_yes_no_expendable_reserves___in_days>
      <_03_12_total_unrestricted_net_assets>
        200444.00
      </_03_12_total_unrestricted_net_assets>
      <_03_08_land__buildings_and_equipment__net>
        169185.64
      </_03_08_land__buildings_and_equipment__net>
      <_03_11_total_debt>191343.00</_03_11_total_debt>
      <_03_08_land__buildings_and_equipment__net>
        169185.64
      </_03_08_land__buildings_and_equipment__net>
      <_03_11_total_debt>191343.00</_03_11_total_debt>
      <_04_08_total_expenses>310930.00</_04_08_total_expenses>
      <_04_09_total_depreciation_expense>
        325215.00
      </_04_09_total_depreciation_expense>
      <_04_ratio_expendable_reserves______of_total_cash_expenses>
        -14.032
      </_04_ratio_expendable_reserves______of_total_cash_expenses>
      <_04_yes_no_expendable_reserves______of_total_cash_expenses>
        Yes
      </_04_yes_no_expendable_reserves______of_total_cash_expenses>
      <_05_ratio_cash_available_to_deferred_revenues>
        0.35
      </_05_ratio_cash_available_to_deferred_revenues>
      <_05_yes_no_cash_available_to_deferred_revenues>
        Yes
      </_05_yes_no_cash_available_to_deferred_revenues>
      <_03_02_total_cash>117555.00</_03_02_total_cash>
      <_03_03_non_endowment_investments>
        130454.00
      </_03_03_non_endowment_investments>
      <_03_10_deferred_revenue>183949.00</_03_10_deferred_revenue>
      <_06_ratio_liquidity_ratio>-48.72</_06_ratio_liquidity_ratio>
      <_06_yes_no_liquidity_ratio>Yes</_06_yes_no_liquidity_ratio>
      <_03_09_current_liabilities>178858.00</_03_09_current_liabilities>
      <_07a_ratio_as_per_statement_of_cash_flows>
        382645
      </_07a_ratio_as_per_statement_of_cash_flows>
      <_07a_yes_no_as_per_statement_of_cash_flows>
        Yes
      </_07a_yes_no_as_per_statement_of_cash_flows>
      <_07b_ratio_depreciation_expenses_on_3_7_year_assets>
        104356
      </_07b_ratio_depreciation_expenses_on_3_7_year_assets>
      <_07b_yes_no_depreciation_expenses_on_3_7_year_assets>
        Yes
      </_07b_yes_no_depreciation_expenses_on_3_7_year_assets>
      <_07c_ratio_over_under_benchmark>278289</_07c_ratio_over_under_benchmark>
      <_07c_yes_no_over_under_benchmark>Yes</_07c_yes_no_over_under_benchmark>
      <update_id>1701460985308</update_id>
    </record>
    <record>
      <fiscal_ye_date_formatted_year>2023</fiscal_ye_date_formatted_year>
      <_01_ratio_students_enrollment>6600</_01_ratio_students_enrollment>
      <_01a_ratio_students_enrollment___change>
        0.017
      </_01a_ratio_students_enrollment___change>
      <_01b_ratio_students_enrollment_average>
        6544
      </_01b_ratio_students_enrollment_average>
      <_01c_ratio_students_enrollment_peak_enrolmment>
        8001
      </_01c_ratio_students_enrollment_peak_enrolmment>
      <_02_ratio_student_faculty_ratio>0.0519</_02_ratio_student_faculty_ratio>
      <main_queryregions>SO</main_queryregions>
      <_01_yes_no_students_enrollment>Yes</_01_yes_no_students_enrollment>
      <_01c_yes_no_students_enrollment_peak_enrolmment>
        Yes
      </_01c_yes_no_students_enrollment_peak_enrolmment>
      <_02_yes_no_student_faculty_ratio>Yes</_02_yes_no_student_faculty_ratio>
      <_01_03_ft_teachers>302</_01_03_ft_teachers>
      <_01_05_pt_teachers>81</_01_05_pt_teachers>
      <_01_01_students_average_enrollment>
        6600
      </_01_01_students_average_enrollment>
      <_03_ratio_expendable_reserves___in_days>
        -4526
      </_03_ratio_expendable_reserves___in_days>
      <_03_yes_no_expendable_reserves___in_days>
        Yes
      </_03_yes_no_expendable_reserves___in_days>
      <_03_12_total_unrestricted_net_assets>
        199001.00
      </_03_12_total_unrestricted_net_assets>
      <_03_08_land__buildings_and_equipment__net>
        169185.64
      </_03_08_land__buildings_and_equipment__net>
      <_03_11_total_debt>192343.00</_03_11_total_debt>
      <_03_08_land__buildings_and_equipment__net>
        169185.64
      </_03_08_land__buildings_and_equipment__net>
      <_03_11_total_debt>192343.00</_03_11_total_debt>
      <_04_08_total_expenses>326422.00</_04_08_total_expenses>
      <_04_09_total_depreciation_expense>
        342470.00
      </_04_09_total_depreciation_expense>
      <_04_ratio_expendable_reserves______of_total_cash_expenses>
        -12.400
      </_04_ratio_expendable_reserves______of_total_cash_expenses>
      <_04_yes_no_expendable_reserves______of_total_cash_expenses>
        Yes
      </_04_yes_no_expendable_reserves______of_total_cash_expenses>
      <_05_ratio_cash_available_to_deferred_revenues>
        0.27
      </_05_ratio_cash_available_to_deferred_revenues>
      <_05_yes_no_cash_available_to_deferred_revenues>
        Yes
      </_05_yes_no_cash_available_to_deferred_revenues>
      <_03_02_total_cash>112344.00</_03_02_total_cash>
      <_03_03_non_endowment_investments>
        123444.00
      </_03_03_non_endowment_investments>
      <_03_10_deferred_revenue>184939.00</_03_10_deferred_revenue>
      <_06_ratio_liquidity_ratio>-8.98</_06_ratio_liquidity_ratio>
      <_06_yes_no_liquidity_ratio>Yes</_06_yes_no_liquidity_ratio>
      <_03_09_current_liabilities>158676.00</_03_09_current_liabilities>
      <_07a_ratio_as_per_statement_of_cash_flows>
        367216
      </_07a_ratio_as_per_statement_of_cash_flows>
      <_07a_yes_no_as_per_statement_of_cash_flows>
        Yes
      </_07a_yes_no_as_per_statement_of_cash_flows>
      <_07b_ratio_depreciation_expenses_on_3_7_year_assets>
        102444
      </_07b_ratio_depreciation_expenses_on_3_7_year_assets>
      <_07b_yes_no_depreciation_expenses_on_3_7_year_assets>
        Yes
      </_07b_yes_no_depreciation_expenses_on_3_7_year_assets>
      <_07c_ratio_over_under_benchmark>264772</_07c_ratio_over_under_benchmark>
      <_07c_yes_no_over_under_benchmark>Yes</_07c_yes_no_over_under_benchmark>
      <update_id>1701460985308</update_id>
    </record>
    <record>
      <fiscal_ye_date_formatted_year>2023</fiscal_ye_date_formatted_year>
      <_01_ratio_students_enrollment>5709</_01_ratio_students_enrollment>
      <_01a_ratio_students_enrollment___change>
        -0.120
      </_01a_ratio_students_enrollment___change>
      <_01b_ratio_students_enrollment_average>
        6098
      </_01b_ratio_students_enrollment_average>
      <_01c_ratio_students_enrollment_peak_enrolmment>
        13493
      </_01c_ratio_students_enrollment_peak_enrolmment>
      <_02_ratio_student_faculty_ratio>3.3262</_02_ratio_student_faculty_ratio>
      <main_queryregions>SO</main_queryregions>
      <_01_yes_no_students_enrollment>Yes</_01_yes_no_students_enrollment>
      <_01c_yes_no_students_enrollment_peak_enrolmment>
        Yes
      </_01c_yes_no_students_enrollment_peak_enrolmment>
      <_02_yes_no_student_faculty_ratio>Yes</_02_yes_no_student_faculty_ratio>
      <_01_03_ft_teachers>565</_01_03_ft_teachers>
      <_01_05_pt_teachers>36847.179487179</_01_05_pt_teachers>
      <_01_01_students_average_enrollment>
        5709
      </_01_01_students_average_enrollment>
      <_03_ratio_expendable_reserves___in_days>
        -9393
      </_03_ratio_expendable_reserves___in_days>
      <_03_yes_no_expendable_reserves___in_days>
        Yes
      </_03_yes_no_expendable_reserves___in_days>
      <_03_12_total_unrestricted_net_assets>
        200324.10
      </_03_12_total_unrestricted_net_assets>
      <_03_08_land__buildings_and_equipment__net>
        169185.64
      </_03_08_land__buildings_and_equipment__net>
      <_03_11_total_debt>192539.49</_03_11_total_debt>
      <_03_08_land__buildings_and_equipment__net>
        169185.64
      </_03_08_land__buildings_and_equipment__net>
      <_03_11_total_debt>192539.49</_03_11_total_debt>
      <_04_08_total_expenses>278170.26</_04_08_total_expenses>
      <_04_09_total_depreciation_expense>
        285954.87
      </_04_09_total_depreciation_expense>
      <_04_ratio_expendable_reserves______of_total_cash_expenses>
        -25.733
      </_04_ratio_expendable_reserves______of_total_cash_expenses>
      <_04_yes_no_expendable_reserves______of_total_cash_expenses>
        Yes
      </_04_yes_no_expendable_reserves______of_total_cash_expenses>
      <_05_ratio_cash_available_to_deferred_revenues>
        0.37
      </_05_ratio_cash_available_to_deferred_revenues>
      <_05_yes_no_cash_available_to_deferred_revenues>
        Yes
      </_05_yes_no_cash_available_to_deferred_revenues>
      <_03_02_total_cash>122477.95</_03_02_total_cash>
      <_03_03_non_endowment_investments>
        130262.56
      </_03_03_non_endowment_investments>
      <_03_10_deferred_revenue>184754.87</_03_10_deferred_revenue>
      <_06_ratio_liquidity_ratio>-32.47</_06_ratio_liquidity_ratio>
      <_06_yes_no_liquidity_ratio>Yes</_06_yes_no_liquidity_ratio>
      <_03_09_current_liabilities>176970.26</_03_09_current_liabilities>
      <_07a_ratio_as_per_statement_of_cash_flows>
        324878
      </_07a_ratio_as_per_statement_of_cash_flows>
      <_07a_yes_no_as_per_statement_of_cash_flows>
        Yes
      </_07a_yes_no_as_per_statement_of_cash_flows>
      <_07b_ratio_depreciation_expenses_on_3_7_year_assets>
        106909
      </_07b_ratio_depreciation_expenses_on_3_7_year_assets>
      <_07b_yes_no_depreciation_expenses_on_3_7_year_assets>
        Yes
      </_07b_yes_no_depreciation_expenses_on_3_7_year_assets>
      <_07c_ratio_over_under_benchmark>217969</_07c_ratio_over_under_benchmark>
      <_07c_yes_no_over_under_benchmark>Yes</_07c_yes_no_over_under_benchmark>
      <update_id>1701357783039</update_id>
    </record>
  </qdbapi>
`;
const xmlClientString = `
  <qdbapi>
    <record>
      <fiscal_ye_date_formatted_year>2019</fiscal_ye_date_formatted_year>
      <related_client>3197</related_client>
      <_01_ratio_students_enrollment>2000</_01_ratio_students_enrollment>
      <_01a_ratio_students_enrollment___change />
      <_01b_ratio_students_enrollment_average />
      <_01c_ratio_students_enrollment_peak_enrolmment>
        7000
      </_01c_ratio_students_enrollment_peak_enrolmment>
      <_02_ratio_student_faculty_ratio>11.5000</_02_ratio_student_faculty_ratio>
      <main_queryregions>MW</main_queryregions>
      <_03_ratio_expendable_reserves___in_days>
        -9271
      </_03_ratio_expendable_reserves___in_days>
      <_03_bench_rating_expendable_reserves___in_days>
        Action Required
      </_03_bench_rating_expendable_reserves___in_days>
      <_04_ratio_expendable_reserves______of_total_cash_expenses>
        -25.400
      </_04_ratio_expendable_reserves______of_total_cash_expenses>
      <_04_benchmark_rating_expendable_reserves______of_total_cash_expenses>
        Action Required
      </_04_benchmark_rating_expendable_reserves______of_total_cash_expenses>
      <_05_ratio_cash_available_to_deferred_revenues>
        0.36
      </_05_ratio_cash_available_to_deferred_revenues>
      <_06_ratio_liquidity_ratio>-31.80</_06_ratio_liquidity_ratio>
      <_06_bench_rating_liquidity_ratio>
        Action Required
      </_06_bench_rating_liquidity_ratio>
      <_07a_ratio_as_per_statement_of_cash_flows>
        207000
      </_07a_ratio_as_per_statement_of_cash_flows>
      <_07b_ratio_depreciation_expenses_on_3_7_year_assets>
        67000
      </_07b_ratio_depreciation_expenses_on_3_7_year_assets>
      <_07c_ratio_over_under_benchmark>140000</_07c_ratio_over_under_benchmark>
      <_07c_bench_rating_over_under_benchmark>
        Good
      </_07c_bench_rating_over_under_benchmark>
      <update_id>1698857103692</update_id>
    </record>
    <record>
      <fiscal_ye_date_formatted_year>2020</fiscal_ye_date_formatted_year>
      <related_client>3197</related_client>
      <_01_ratio_students_enrollment>9000</_01_ratio_students_enrollment>
      <_01a_ratio_students_enrollment___change>
        3.500
      </_01a_ratio_students_enrollment___change>
      <_01b_ratio_students_enrollment_average>
        5500
      </_01b_ratio_students_enrollment_average>
      <_01c_ratio_students_enrollment_peak_enrolmment>
        19000
      </_01c_ratio_students_enrollment_peak_enrolmment>
      <_02_ratio_student_faculty_ratio>5.9444</_02_ratio_student_faculty_ratio>
      <main_queryregions>MW</main_queryregions>
      <_03_ratio_expendable_reserves___in_days>
        -9454
      </_03_ratio_expendable_reserves___in_days>
      <_03_bench_rating_expendable_reserves___in_days>
        Action Required
      </_03_bench_rating_expendable_reserves___in_days>
      <_04_ratio_expendable_reserves______of_total_cash_expenses>
        -25.900
      </_04_ratio_expendable_reserves______of_total_cash_expenses>
      <_04_benchmark_rating_expendable_reserves______of_total_cash_expenses>
        Action Required
      </_04_benchmark_rating_expendable_reserves______of_total_cash_expenses>
      <_05_ratio_cash_available_to_deferred_revenues>
        0.37
      </_05_ratio_cash_available_to_deferred_revenues>
      <_06_ratio_liquidity_ratio>-32.80</_06_ratio_liquidity_ratio>
      <_06_bench_rating_liquidity_ratio>
        Action Required
      </_06_bench_rating_liquidity_ratio>
      <_07a_ratio_as_per_statement_of_cash_flows>
        419000
      </_07a_ratio_as_per_statement_of_cash_flows>
      <_07b_ratio_depreciation_expenses_on_3_7_year_assets>
        139000
      </_07b_ratio_depreciation_expenses_on_3_7_year_assets>
      <_07c_ratio_over_under_benchmark>280000</_07c_ratio_over_under_benchmark>
      <_07c_bench_rating_over_under_benchmark>
        Good
      </_07c_bench_rating_over_under_benchmark>
      <update_id>1698853160919</update_id>
    </record>
    <record>
      <fiscal_ye_date_formatted_year>2021</fiscal_ye_date_formatted_year>
      <related_client>3197</related_client>
      <_01_ratio_students_enrollment>8462</_01_ratio_students_enrollment>
      <_01a_ratio_students_enrollment___change>
        -0.060
      </_01a_ratio_students_enrollment___change>
      <_01b_ratio_students_enrollment_average>
        8731
      </_01b_ratio_students_enrollment_average>
      <_01c_ratio_students_enrollment_peak_enrolmment>
        20000
      </_01c_ratio_students_enrollment_peak_enrolmment>
      <_02_ratio_student_faculty_ratio>6.9545</_02_ratio_student_faculty_ratio>
      <main_queryregions>MW</main_queryregions>
      <_03_ratio_expendable_reserves___in_days>
        -9393
      </_03_ratio_expendable_reserves___in_days>
      <_03_bench_rating_expendable_reserves___in_days>
        Action Required
      </_03_bench_rating_expendable_reserves___in_days>
      <_04_ratio_expendable_reserves______of_total_cash_expenses>
        -25.733
      </_04_ratio_expendable_reserves______of_total_cash_expenses>
      <_04_benchmark_rating_expendable_reserves______of_total_cash_expenses>
        Action Required
      </_04_benchmark_rating_expendable_reserves______of_total_cash_expenses>
      <_05_ratio_cash_available_to_deferred_revenues>
        0.37
      </_05_ratio_cash_available_to_deferred_revenues>
      <_06_ratio_liquidity_ratio>-32.47</_06_ratio_liquidity_ratio>
      <_06_bench_rating_liquidity_ratio>
        Action Required
      </_06_bench_rating_liquidity_ratio>
      <_07a_ratio_as_per_statement_of_cash_flows>
        481538
      </_07a_ratio_as_per_statement_of_cash_flows>
      <_07b_ratio_depreciation_expenses_on_3_7_year_assets>
        158462
      </_07b_ratio_depreciation_expenses_on_3_7_year_assets>
      <_07c_ratio_over_under_benchmark>323077</_07c_ratio_over_under_benchmark>
      <_07c_bench_rating_over_under_benchmark>
        Good
      </_07c_bench_rating_over_under_benchmark>
      <update_id>1698853160919</update_id>
    </record>
    <record>
      <fiscal_ye_date_formatted_year>2022</fiscal_ye_date_formatted_year>
      <related_client>3197</related_client>
      <_01_ratio_students_enrollment>6487</_01_ratio_students_enrollment>
      <_01a_ratio_students_enrollment___change>
        -0.233
      </_01a_ratio_students_enrollment___change>
      <_01b_ratio_students_enrollment_average>
        7475
      </_01b_ratio_students_enrollment_average>
      <_01c_ratio_students_enrollment_peak_enrolmment>
        15333
      </_01c_ratio_students_enrollment_peak_enrolmment>
      <_02_ratio_student_faculty_ratio>6.9545</_02_ratio_student_faculty_ratio>
      <main_queryregions>MW</main_queryregions>
      <_03_ratio_expendable_reserves___in_days>
        -9393
      </_03_ratio_expendable_reserves___in_days>
      <_03_bench_rating_expendable_reserves___in_days>
        Action Required
      </_03_bench_rating_expendable_reserves___in_days>
      <_04_ratio_expendable_reserves______of_total_cash_expenses>
        -25.733
      </_04_ratio_expendable_reserves______of_total_cash_expenses>
      <_04_benchmark_rating_expendable_reserves______of_total_cash_expenses>
        Action Required
      </_04_benchmark_rating_expendable_reserves______of_total_cash_expenses>
      <_05_ratio_cash_available_to_deferred_revenues>
        0.37
      </_05_ratio_cash_available_to_deferred_revenues>
      <_06_ratio_liquidity_ratio>-32.47</_06_ratio_liquidity_ratio>
      <_06_bench_rating_liquidity_ratio>
        Action Required
      </_06_bench_rating_liquidity_ratio>
      <_07a_ratio_as_per_statement_of_cash_flows>
        369179
      </_07a_ratio_as_per_statement_of_cash_flows>
      <_07b_ratio_depreciation_expenses_on_3_7_year_assets>
        121487
      </_07b_ratio_depreciation_expenses_on_3_7_year_assets>
      <_07c_ratio_over_under_benchmark>247692</_07c_ratio_over_under_benchmark>
      <_07c_bench_rating_over_under_benchmark>
        Good
      </_07c_bench_rating_over_under_benchmark>
      <update_id>1698853160919</update_id>
    </record>
    <record>
      <fiscal_ye_date_formatted_year>2023</fiscal_ye_date_formatted_year>
      <related_client>3197</related_client>
      <_01_ratio_students_enrollment>5709</_01_ratio_students_enrollment>
      <_01a_ratio_students_enrollment___change>
        -0.120
      </_01a_ratio_students_enrollment___change>
      <_01b_ratio_students_enrollment_average>
        6098
      </_01b_ratio_students_enrollment_average>
      <_01c_ratio_students_enrollment_peak_enrolmment>
        13493
      </_01c_ratio_students_enrollment_peak_enrolmment>
      <_02_ratio_student_faculty_ratio>6.9545</_02_ratio_student_faculty_ratio>
      <main_queryregions>MW</main_queryregions>
      <_03_ratio_expendable_reserves___in_days>
        -9393
      </_03_ratio_expendable_reserves___in_days>
      <_03_bench_rating_expendable_reserves___in_days>
        Action Required
      </_03_bench_rating_expendable_reserves___in_days>
      <_04_ratio_expendable_reserves______of_total_cash_expenses>
        -25.733
      </_04_ratio_expendable_reserves______of_total_cash_expenses>
      <_04_benchmark_rating_expendable_reserves______of_total_cash_expenses>
        Action Required
      </_04_benchmark_rating_expendable_reserves______of_total_cash_expenses>
      <_05_ratio_cash_available_to_deferred_revenues>
        0.37
      </_05_ratio_cash_available_to_deferred_revenues>
      <_06_ratio_liquidity_ratio>-32.47</_06_ratio_liquidity_ratio>
      <_06_bench_rating_liquidity_ratio>
        Action Required
      </_06_bench_rating_liquidity_ratio>
      <_07a_ratio_as_per_statement_of_cash_flows>
        324878
      </_07a_ratio_as_per_statement_of_cash_flows>
      <_07b_ratio_depreciation_expenses_on_3_7_year_assets>
        106909
      </_07b_ratio_depreciation_expenses_on_3_7_year_assets>
      <_07c_ratio_over_under_benchmark>217969</_07c_ratio_over_under_benchmark>
      <_07c_bench_rating_over_under_benchmark>
        Good
      </_07c_bench_rating_over_under_benchmark>
      <update_id>1698853160919</update_id>
    </record>
  </qdbapi>
`;

const parser = new DOMParser();
const parserClient = new DOMParser();
const xmlPeerDoc = parser.parseFromString(xmlPeerString, 'text/xml');
const xmlClientDoc = parser.parseFromString(xmlClientString, 'text/xml');
const recordsPeer = xmlPeerDoc.querySelectorAll('record');
const recordsClient = xmlClientDoc.querySelectorAll('record');

document.addEventListener('DOMContentLoaded', () => {
  findUniqueYears(recordsClient);

  addUniqueRegionsToOptionsSelectRegionDropdown(regions_Array);

  displayEnrollmentComponent();
  displayReportComponent();

  runApiMain();
});

const findUniqueYears = (data) => {
  recordsClient.forEach((item) => {
    const yearElement = item.querySelector('fiscal_ye_date_formatted_year');
    if (yearElement) {
      const year = yearElement.textContent;

      // Check if the year is not already in yearsData_Array to ensure uniqueness
      if (!yearsData_Array.includes(year)) {
        yearsData_Array.push(year);
      }
    }
  });

  yearsData_Array.sort();

  //nav-component
  addUniqueYearsToOptionsSelectDropdown(yearsData_Array);
};

const insertDataIntoObject = (
  type,
  year,
  object,
  dataKey,
  record,
  child,
  dynamicValueClientPeer
) => {
  const innerData =
    record.querySelector(child).innerHTML.split('').length > 0
      ? record.querySelector(child).innerHTML.trim()
      : 0;

  if (type === 'client') {
    if (!object[dataKey]) {
      object[dataKey] = {};
    }
    if (!object[dataKey][year]) {
      object[dataKey][year] = {};
    }
    object[dataKey][year].value = innerData;
    const benchmarkField =
      dynamicValueClientPeer &&
      record.querySelector(dynamicValueClientPeer).textContent.trim();
    object[dataKey][year].benchmark = benchmarkField;
  } else {
    // type === 'peer'

    const yesNoField =
      dynamicValueClientPeer &&
      record.querySelector(dynamicValueClientPeer).textContent.trim();

    if (yesNoField == 'Yes') {
      if (!object[dataKey]) {
        object[dataKey] = {};
      }
      if (!object[dataKey][year]) {
        object[dataKey][year] = [];
      }
      if (!object[dataKey]['total']) {
        object[dataKey]['total'] = [];
      }

      object[dataKey][year].push(innerData);
      object[dataKey]['total'].push(innerData);
    }
  }
};

const processCashData = (years, recordsPeer, recordsClient) => {
  const object = {};

  years.forEach((year) => {
    const filteredPeerRecords = [...recordsPeer].filter((record) => {
      const fiscalYear = record.querySelector(
        'fiscal_ye_date_formatted_year'
      ).textContent;

      return fiscalYear.includes(year.toString());
    });
    filteredPeerRecords.forEach((record) => {
      // expendableReserves_inDays
      insertDataIntoObject(
        'peer',
        year,
        object,
        'expendableReserves_inDays_Peer',
        record,
        '_03_ratio_expendable_reserves___in_days',
        '_03_yes_no_expendable_reserves___in_days'
      );
      insertDataIntoObject(
        'peer',
        year,
        object,
        'unrestrictedNetAssets',
        record,
        '_03_12_total_unrestricted_net_assets',
        '_03_yes_no_expendable_reserves___in_days'
      );
      insertDataIntoObject(
        'peer',
        year,
        object,
        'landBuildingsEquipmentNet',
        record,
        '_03_08_land__buildings_and_equipment__net',
        '_03_yes_no_expendable_reserves___in_days'
      );
      insertDataIntoObject(
        'peer',
        year,
        object,
        'totalDebt',
        record,
        '_03_11_total_debt',
        '_03_yes_no_expendable_reserves___in_days'
      );
      insertDataIntoObject(
        'peer',
        year,
        object,
        'totalDepreciationExpense',
        record,
        '_04_09_total_depreciation_expense',
        '_03_yes_no_expendable_reserves___in_days'
      );
      insertDataIntoObject(
        'peer',
        year,
        object,
        'totalExpense',
        record,
        '_04_08_total_expenses',
        '_03_yes_no_expendable_reserves___in_days'
      );

      // expaendableReserves_Percent
      insertDataIntoObject(
        'peer',
        year,
        object,
        'expendableReserves_Percent_Peer',
        record,
        '_04_ratio_expendable_reserves______of_total_cash_expenses',
        '_04_yes_no_expendable_reserves______of_total_cash_expenses'
      );

      // cashAvailableDeferred
      insertDataIntoObject(
        'peer',
        year,
        object,
        'cashAvailableDeferred_Peer',
        record,
        '_05_ratio_cash_available_to_deferred_revenues',
        '_05_yes_no_cash_available_to_deferred_revenues'
      );
      insertDataIntoObject(
        'peer',
        year,
        object,
        'totalCash',
        record,
        '_03_02_total_cash',
        '_05_yes_no_cash_available_to_deferred_revenues'
      );
      insertDataIntoObject(
        'peer',
        year,
        object,
        'nonEndowmentInvestments',
        record,
        '_03_03_non_endowment_investments',
        '_05_yes_no_cash_available_to_deferred_revenues'
      );
      insertDataIntoObject(
        'peer',
        year,
        object,
        'deferredRevenue',
        record,
        '_03_10_deferred_revenue',
        '_05_yes_no_cash_available_to_deferred_revenues'
      );

      // liquidityRatio
      insertDataIntoObject(
        'peer',
        year,
        object,
        'liquidityRatio_Peer',
        record,
        '_06_ratio_liquidity_ratio',
        '_06_yes_no_liquidity_ratio'
      );
      insertDataIntoObject(
        'peer',
        year,
        object,
        'currentLiabilities',
        record,
        '_03_09_current_liabilities',
        '_06_yes_no_liquidity_ratio'
      );

      // netCashUsedOperating_asPerStatementCash
      insertDataIntoObject(
        'peer',
        year,
        object,
        'netCashUsedOperating_asPerStatementCash_Peer',
        record,
        '_07a_ratio_as_per_statement_of_cash_flows',
        '_07a_yes_no_as_per_statement_of_cash_flows'
      );

      // netCashUsedOperating_depreciation
      insertDataIntoObject(
        'peer',
        year,
        object,
        'netCashUsedOperating_depreciation_Peer',
        record,
        '_07b_ratio_depreciation_expenses_on_3_7_year_assets',
        '_07b_yes_no_depreciation_expenses_on_3_7_year_assets'
      );
    });

    const filteredClientRecords = [...recordsClient].filter((record) => {
      const fiscalYear = record.querySelector(
        'fiscal_ye_date_formatted_year'
      ).textContent;
      return fiscalYear.includes(year.toString());
    });
    filteredClientRecords.forEach((record) => {
      // expendableReserves_inDays
      insertDataIntoObject(
        'client',
        year,
        object,
        'expendableReserves_inDays_Client',
        record,
        '_03_ratio_expendable_reserves___in_days',
        '_03_bench_rating_expendable_reserves___in_days'
      );
      // expendableReserves_Percent
      insertDataIntoObject(
        'client',
        year,
        object,
        'expendableReserves_Percent_Client',
        record,
        '_04_ratio_expendable_reserves______of_total_cash_expenses',
        '_04_benchmark_rating_expendable_reserves______of_total_cash_expenses'
      );
      // cashAvailableDeferred
      insertDataIntoObject(
        'client',
        year,
        object,
        'cashAvailableDeferred_Client',
        record,
        '_05_ratio_cash_available_to_deferred_revenues'
      );
      // liquidityRatio
      insertDataIntoObject(
        'client',
        year,
        object,
        'liquidityRatio_Client',
        record,
        '_06_ratio_liquidity_ratio',
        '_06_bench_rating_liquidity_ratio'
      );
      // netCashUsedOperating_asPerStatementCash
      insertDataIntoObject(
        'client',
        year,
        object,
        'netCashUsedOperating_asPerStatementCash_Client',
        record,
        '_07a_ratio_as_per_statement_of_cash_flows'
      );
      // netCashUsedOperating_depreciation
      insertDataIntoObject(
        'client',
        year,
        object,
        'netCashUsedOperating_depreciation_Client',
        record,
        '_07b_ratio_depreciation_expenses_on_3_7_year_assets'
      );
    });
  });

  // console.log(object);
  localStorage.removeItem('cashData');
  localStorage.setItem('cashData', JSON.stringify(object));
};

const processEnrollmentData = (years, recordsPeer, recordsClient) => {
  const object = {};

  years.forEach((year) => {
    const filteredPeerRecords = [...recordsPeer].filter((record) => {
      const fiscalYear = record.querySelector(
        'fiscal_ye_date_formatted_year'
      ).textContent;

      return fiscalYear.includes(year.toString());
    });
    filteredPeerRecords.forEach((record) => {
      insertDataIntoObject(
        'peer',
        year,
        object,
        'studentAverageEnrollment_Peer',
        record,
        '_01_ratio_students_enrollment',
        '_01_yes_no_students_enrollment'
      );
      insertDataIntoObject(
        'peer',
        year,
        object,
        'studentAverageEnrollment_Peak_Peer',
        record,
        '_01c_ratio_students_enrollment_peak_enrolmment',
        '_01c_yes_no_students_enrollment_peak_enrolmment'
      );
      insertDataIntoObject(
        'peer',
        year,
        object,
        'studentsFacilityRatio_Peer',
        record,
        '_02_ratio_student_faculty_ratio',
        '_02_yes_no_student_faculty_ratio'
      );
      insertDataIntoObject(
        'peer',
        year,
        object,
        'fullTimeTeachers_Peer',
        record,
        '_01_03_ft_teachers',
        '_02_yes_no_student_faculty_ratio'
      );
      insertDataIntoObject(
        'peer',
        year,
        object,
        'partTimeTeachers_Peer',
        record,
        '_01_05_pt_teachers',
        '_02_yes_no_student_faculty_ratio'
      );
      insertDataIntoObject(
        'peer',
        year,
        object,
        'studentAverageEnrollment_Main',
        record,
        '_01_01_students_average_enrollment',
        '_02_yes_no_student_faculty_ratio'
      );
    });

    const filteredClientRecords = [...recordsClient].filter((record) => {
      const fiscalYear = record.querySelector(
        'fiscal_ye_date_formatted_year'
      ).textContent;
      return fiscalYear.includes(year.toString());
    });
    filteredClientRecords.forEach((record) => {
      insertDataIntoObject(
        'client',
        year,
        object,
        'studentAverageEnrollment_Client',
        record,
        '_01_ratio_students_enrollment'
      );
      insertDataIntoObject(
        'client',
        year,
        object,
        'studentAverageEnrollment_PercentChange_Client',
        record,
        '_01a_ratio_students_enrollment___change'
      );
      insertDataIntoObject(
        'client',
        year,
        object,
        'studentAverageEnrollment_Average_Client',
        record,
        '_01b_ratio_students_enrollment_average'
      );
      insertDataIntoObject(
        'client',
        year,
        object,
        'studentAverageEnrollment_Peak_Client',
        record,
        '_01c_ratio_students_enrollment_peak_enrolmment'
      );
      insertDataIntoObject(
        'client',
        year,
        object,
        'studentsFacilityRatio_Client',
        record,
        '_02_ratio_student_faculty_ratio'
      );
    });
  });

  localStorage.removeItem('enrollmentData');
  localStorage.setItem('enrollmentData', JSON.stringify(object));
};

const addColumnsToOtherRows = (idName, year) => {
  const rows = document.querySelectorAll(`#${idName} + tbody tr`);

  rows.forEach((row) => {
    const tdElement = document.createElement('td');
    // You can customize the content of the new columns as needed
    tdElement.textContent = 'New Data'; // Change this line accordingly
    row.appendChild(tdElement);
  });
};

const runApiMain = () => {
  const run_btn = document.querySelector('#run');

  run_btn.addEventListener('click', () => {
    try {
      const selectedYears = getSelectedYearsFromLocalStorage();

      // After processing, save selectedYears_Set to localStorage
      const selectedYearsArray = Array.from(selectedYears_Set).sort(
        (a, b) => a - b
      );
      localStorage.setItem('selectedYears', JSON.stringify(selectedYearsArray));

      processEnrollmentData(selectedYears, recordsPeer, recordsClient);
      processCashData(selectedYears, recordsPeer, recordsClient);
      displayEnrollmentComponent();
      displayReportComponent();
    } catch (err) {
      console.error(err);
    }
  });
};
