<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="qdbapi">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="apptoken" type="xs:string" />
                <xs:element name="field" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:simpleContent>
                            <xs:extension base="xs:string">
                                <xs:attribute name="fid" type="xs:integer" use="required" />
                                <xs:attribute name="filename" use="required" fixed="image.png" />
                            </xs:extension>
                        </xs:simpleContent>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>