/**
 * Fix Unicode encoding issues in content, particularly apostrophes
 * @param {string} content - The content string to fix
 * @returns {string} - Content with properly encoded Unicode characters
 */
function fixUnicodeCharacters(content) {
  if (typeof content !== 'string') {
    return content;
  }

  // Replace common problematic Unicode characters that display as �
  const unicodeReplacements = {
    // Apostrophe variations that often cause encoding issues
    '\u2019': "'",     // Right single quotation mark (smart apostrophe)
    '\u2018': "'",     // Left single quotation mark  
    '\u00B4': "'",     // Acute accent
    '\u0060': "'",     // Grave accent
    '\u02BC': "'",     // Modifier letter apostrophe
    
    // Quote variations
    '\u201C': '"',     // Left double quotation mark
    '\u201D': '"',     // Right double quotation mark
    '\u201E': '"',     // Double low-9 quotation mark
    '\u201F': '"',     // Double high-reversed-9 quotation mark
    
    // Dash variations
    '\u2013': '-',     // En dash
    '\u2014': '--',    // Em dash
    '\u2015': '--',    // Horizontal bar
    
    // Other common problematic characters
    '\u2026': '...',   // Horizontal ellipsis
    '\u00A0': ' ',     // Non-breaking space
    '\uFFFD': "'",     // Unicode replacement character (often appears as �)
  };

  let fixedContent = content;

  // Apply each replacement
  Object.entries(unicodeReplacements).forEach(([problematic, replacement]) => {
    fixedContent = fixedContent.replace(new RegExp(problematic, 'g'), replacement);
  });

  // Additional cleanup for any remaining � characters that might be malformed apostrophes
  fixedContent = fixedContent.replace(/\uFFFD/g, "'");

  return fixedContent;
}

// Define "What Does This Mean" content arrays from todo_nov18_25.md
const daysExpendable_whatDoesThisMean = [
  `This ratio tells how many days of operating expenses are available in net asset reserves. The difference between this and Ratio 2 is that this ratio uses net asset reserves, which take into account the accrual of current assets and current liabilities.`,
  `The term expendable net assets represents the total resources available to spend on operations, excluding future gifts made or revenues generated by the church. Think of it as how long you could live on a savings account.`,
  `Expendable net assets consist of net assets without donor restrictions, undesignated (formerly referred to as unrestricted, undesignated net assets), which are net assets that result from achieving positive net income year after year in the "without donor restrictions" column of the statement of activities. This is the result of spending fewer contributions without donor restrictions than were taken in, or of the positive operations of other ministries within the church, such as a bookstore or a media ministry. The total of positive operations from these revenue sources (after expenses) produces undesignated net assets without donor restrictions. The balance also includes reserves designated by the board for specific operating purposes, but excludes reserves that represent the church's equity in land, buildings, and equipment.`,
  `The total of the amounts in the numerator is divided by total expenditures less the annual non-cash expense of depreciation. The net result of removing depreciation is to calculate, based on prior expenditures, the cash expenses your church would incur.`,
  `The number of days can be temporarily high if the church has recorded large gifts without donor restrictions that have not been spent at year-end. This is the case for churches with fiscal years ending on December 31, when many attendees give large year-end gifts in order to meet tax-reporting deadlines. The number of days can also appear low if the church incurred a large one-time expenditure that won't be repeated in the future.`,
  `To improve this ratio over the long term, it is necessary to increase undesignated net assets without donor restrictions or board-designated net assets for operations, or both. Achieving positive net income in the "without donor restrictions" column of the statement of activities year after year accomplishes this. Growth of the undesignated net assets without donor restrictions must exceed the rate of increase in the denominator or cash expenses to positively improve this ratio. Conversely, keeping expendable net asset reserves the same but cutting cash expenses will also have a positive impact on this ratio.`,
];

const daysOperatingCash_whatDoesThisMean = [
  `This ratio calculates the days of operating cash and investments on hand to fund annual cash expenditures, but specifically related to very liquid assets. It only considers operating cash and investments, not other current assets and liabilities.`,
  `Operating cash and investments are those resources that do not carry donor restrictions on the assets and are available for the church to spend without restrictions. This number is divided by the sum of expenses plus capitalized interest, which is interest paid in cash but not expensed by the church. This may occur during periods of construction when GAAP requires the church to capitalize this cash expense as part of the cost of the asset being built. Depreciation and amortization are also removed because they represent significant noncash annual expenses recorded by the church. Current debt principal (amounts due next year but not expected to be refinanced) is added back because it represents cash spent, but it is not recorded as an expense in the financial statements. The net effect of these adjustments is to estimate, based on prior expenditures, the annual cash expenditures the church would incur.`,
  `To improve this ratio, operating cash or investments must increase at a rate greater than the denominator (annual cash expenditures). Conversely, keeping operating cash or investments the same but cutting annual cash expenditures will also have a positive impact on this ratio.`,
];

const liquidityRatio_whatDoesThisMean = [
  `This ratio measures how the church's most liquid assets (operating cash, investments, and accounts receivable) are able to cover current operating liabilities. These operating liabilities exclude current debt principal expected to be refinanced within the next year. The ratio also excludes deferred revenues, which do not require an outlay of cash.`,
  `This ratio indicates the church's ability to meet its short-term liabilities using its most liquid assets. To improve this ratio, either operating cash or investments must improve at a rate greater than operating liabilities. Conversely, operating liabilities must either decrease while the operating cash and investments remain consistent or decrease at a lesser rate.`,
];

const cashFlowsFromOperatingActivities_whatDoesThisMean = [
  `This figure represents the cash flow generated from the church's regular activities (such as donations, program fees, and other ministry-related income), compared to the cash spent on salaries, utilities, outreach, and other ministry-related expenses.`,
  `Monitoring cash flow from operating activities is crucial for a church, as it reflects the sustainability of its core mission-driven operations. By tracking this figure, your church can ensure that it has sufficient liquidity to meet its ongoing obligations. This insight can also help inform decisions about future budgeting.`,
  `<u><strong>The Impact of Depreciation and Amortization on Cash Flow and Reserves Ratios</strong></u>`,
  `Ratios 1 and 2 exclude the impact of depreciation and amortization, as they are non-cash expenses. Depreciation and amortization can be troublesome for many, since most churches do not include these expenses in their internal budgets.`,
  `Since nonprofit organizations are not required to pay taxes, many individuals feel it is unnecessary to track depreciation and amortization. For accrual basis financial statements, accounting standards require it; however, it can also be useful for churches to factor depreciation and amortization into their annual budgets and set aside those funds for a reserve.`,
  `Depreciation is supposed to be calculated over the "useful life" of the asset. If a new roof with a cost of $100,000 is expected to last 20 years, the depreciation recorded on a straight line each year would be $5,000. If those same funds were budgeted and reserved by the church, the money would be available to replace the roof after that time. This can be very beneficial for large items. Many churches are surprised by these unbudgeted, high-cost replacements and sometimes even find it necessary to find financing options to take care of necessary facility upkeep. So while depreciation was omitted for these ratios, it is an important factor in providing future cash flows for necessary repairs and replacement in the church.`,
];

const netCashAvailable_whatDoesThisMean = [
  `This measurement calculates the amount of cash available for other uses after the church has satisfied its adjusted current liabilities and cash and investments set aside for projects with donor restrictions (excluding non-cash amounts or pledges receivable from donorrestricted projects) resulting from gifts given by donors who have placed restrictions on their use. Any debt that is part of current liabilities but is expected to be refinanced within the next year is excluded.`,
  `This may be one of the most important measures provided to your church leadership. Many churches today find that senior management (pastoral staff) and the governing board want to know how much cash the church has. The most important question is not "How much do we have?" but rather, "Whose cash is it and how much of it can we spend?" Those are typically two very different answers.`,
  `A net cash availability number factors in the cash required for the immediate future (less than 10 days) to determine what can safely be spent.`,
  `Net assets with donor restrictions are not to be expended for general operating purposes and therefore are excluded from the cash balance. Keep in mind that the portion of net assets with donor restrictions that are supported by pledges receivable are excluded (deducted from total net assets with donor restrictions) as they would have no impact on this cash-based calculation. Some churches have in essence "borrowed" from reserves with donor restrictions because they overspent in operations. This calculation will help management identify if this is happening in your church, so it is crucial to provide this information to decision makers.`,
  `To improve this figure, you must change one or a combination of the following factors:<br />• Increase operating cash or investments<br />• Decrease current liabilities<br />• Decrease operational net assets with donor restrictions`,
];

const debtToContributionsWithout_whatDoesThisMean = [
  `This ratio measures how many times debt is greater than annual contributions without donor restrictions, which are the primary income source for most churches.`,
  `Lenders look at debt as funded by contributions without donor restrictions because those are the resources from which the church will be able to pay mandatory debt service payments. By looking at trends in various congregations, contributions without donor restrictions help the lender determine what debt load the church will be able to handle on top of other required expenditures (salaries, benefits, mission expenses, facility expenses, etc.).`,
  `The best way to improve this ratio is to decrease total debt. Another option is to increase contributions without donor restrictions. However, forecasting an increased revenue source is less certain than a careful plan that intentionally lowers the debt balance.`,
];

const currentRatio_whatDoesThisMean = [
  `This ratio helps determine how easily the church can meet its current obligations through current assets.`,
  `There are differences of opinion as to what the ratio results should be. A ratio of less than 1.0 could be interpreted as a red flag that the church does not have enough in current assets to pay its upcoming liabilities. This could result in the need to borrow from restricted funds or the need to obtain a temporary line of credit to cover short-term obligations. Results this low would also warrant a careful review of the cash flow and reserves ratios and measurements. Your church will need to be aware of this and monitor the ratio on an ongoing basis to avoid being surprised by a cash shortage.`,
  `To improve this ratio, increase current assets at a rate greater than current liabilities. Conversely, your church may decide to pay down current liabilities, but these are usually paid with current assets. The key to improving the ratio is to lower current assets less than current liabilities.`,
];

const mandatoryDebtService_whatDoesThisMean = [
  `This ratio pertains more to the debt service (debt payment requirements), and looks at the percentage of contributions that will be used to make annual debt service payments.`,
  `Although a church may have many revenue sources, lenders typically only consider contributions without donor restrictions when determining how much debt a church can manage.`,
  `To improve this ratio, the church must lower its required annual debt principal and interest payments. Modifying the terms of the debt with the lender should accomplish this. (Note that this may violate the debt covenant and require a bank covenant waiver and payment of related fees.) You can also improve the ratio by maintaining the same debt service payment schedule while increasing contributions without donor restrictions. Obviously, increasing a revenue source carries its own unique challenges.`,
];

const debtPerGivingUnit_whatDoesThisMean = [
  `This measure introduces the concept of a giving unit. A giving unit is usually a group of family members who contribute jointly to the church. A giving unit is also defined as any recurring supporter of the ministry. This excludes the individual who may make a smaller one-time gift supporting an event, such as a short-term mission trip. To identify only the regular recurring giving units, the measure only includes giving units that contribute more than $250 annually to the church.`,
  `This figure is calculated by dividing total debt by giving units. It will vary significantly based on the philosophy, denomination, location, age, size, and demographics of the church. Each church will need to determine the level of debt it is comfortable maintaining or servicing. You will probably encounter varying opinions within your congregation. Some individuals believe that a church should not incur debt while others are very comfortable with a high debt load.`,
  `Lenders believe that debt will be funded by contributions without donor restrictions because typically these are the resources from which the church will be able to pay mandatory debt service payments.`,
];

const debtCoverage_whatDoesThisMean = [
  `This ratio is used to determine how many times a church would be able to cover its current annual debt obligations from current operations. This is a very common debt covenant ratio used by lenders to monitor a church's ability to make annual debt service payments. The results could change dramatically between years based on swings to the change in net assets without donor restrictions. For example, if a church used its reserves to perform more repairs and maintenance to its facility than normal, the increase in expense could cause a much lower positive or even negative change in net assets without donor restrictions. This would adversely affect the ratio and could unexpectedly violate a debt covenant, potentially requiring the church to obtain a bank covenant waiver and pay related fees. The benchmark agreed to by the lender is a key negotiation point, especially with a new lender. It may also factor into the amount of reserves the church leadership deems necessary.`,
  `The change in net assets without donor restrictions is primarily driven by operational decisions that affect things such as the management of budgeted expenses. Successes or failures at developing good stewardship habits in the congregation, resulting in growth or decline of contributions without donor restrictions, can also have a significant effect on this number. Interest expense represents interest payments under the terms of the note.`,
  `The biggest factor impacting this ratio is significant increases or decreases to the change in net assets without donor restrictions. Ministry decisions or necessary additional expenditures as discussed above may drive the decision to spend net assets without donor restrictions and result in a lower positive or negative change in net assets without donor restrictions. While a lower positive or negative change in net assets without donor restrictions may impact this ratio in the current year, it is important to look at the trends and understand the reasons behind ministry decisions to spend resources without donor restrictions. It is also equally important that the effect of these decisions on the ratio is not a last-minute surprise to management or the outside lender. An unexpected result could cause a strain on the relationship with the lender.`,
  `Lowering required annual debt principal and interest payments may also modify the denominator. This is usually done by modifying the terms of the debt with the lender, which may violate the debt covenant. Lower interest expense will also affect the numerator positively. So, increasing change in net assets without donor restrictions is still the best way to improve this ratio.`,
];

const netIncome_whatDoesThisMean = [
  `The purpose of this ratio is to show if the results of the church's general operations are positive or negative, and by how much. In business terms, this shows if the church is making or losing money in its basic day-today function of ministering to the local community. The importance of this ratio is immediately apparent. If a church is losing money in its basic operations over time, eventually it will no longer be viable and will have to close. At some point this church will reach the stage where it is either too late to make the necessary operational changes or it no longer has the funds or the confidence to make them. That point is more easily identified in retrospect, but the net income ratio can provide a bellwether to warn of impending financial distress.`,
  `The change in net assets without donor restrictions (net income or net loss) is a measure of operational results for management. The change in net assets without donor restrictions more closely explains whether management met the anticipated targets for spending or not. The net income ratio defines what percentage of revenues without donor restrictions resulted in the net income. Another way of viewing this ratio is to ask what percentage of revenues was spent during the year.`,
  `One factor to consider when calculating this ratio is that very large one-time events, such as the receipt of a large one-time gift without donor restrictions made at the end of the fiscal year, can significantly influence a church's net income without donor restrictions.`,
  `Your church may not want to have large surpluses every year. You may want to make sure that money is invested in the ministries of the church. However, you need to make sure some reserves are in place. Monitoring this ratio and the trend of it from year to year will help determine the financial health of your church.`,
  `For example, a church may build reserves for a few years to launch a new ministry or a satellite campus. Then for a year or two there will be significant net losses as that ministry begins operating. If the positive years had not happened first, the ministry launch may not have been possible.`,
  `That is why it is more important to monitor the average net income ratio over several years, if possible. Averages that include a few years of surpluses with a couple of years of "investment" followed by a stabilization of income will show how the surpluses and deficits averaged over that period.`,
  `Increasing the change in net assets without donor restrictions will have the single most positive impact on this ratio. As discussed previously, there are many ministry reasons a church may or may not choose to show consistent surpluses. It is because of these reasons that the ratio is also calculated using the average net income over several years, to determine if recent deficits are a one-time issue or a growing, unchecked trend.`,
];

const contrWithoutPerAvgAttAndGU_whatDoesThisMean = [
  `This calculation, which removes the effect of large one-time (unusual) gifts without donor restrictions, can be compared from year to year to see the trends and determine the impact on the church and budget. Another valuable comparison is to calculate what contributions would be if every giving unit made a certain amount (i.e., $50,000 a year) and tithed on that amount. The church could use this measurement to make the congregation aware of what the current giving per giving unit is, and what the projected giving would be if everyone participated.`,
  `Churches today have to look at contributions differently than at any time in the past. Contributions are down, and generational differences are very strong even in the way people contribute to their church. Young people, who are more cause-driven, tend to give to specific purposes and causes and are less interested in giving to general operations. This creates budgeting concerns.`,
  `Churches choose to communicate these needs in various ways. Some annually communicate contributions per giving unit. Others may request contributions towards a specific need and tell the congregation what was received and how the funds were spent, and show pictures of the repairs or replacements.`,
  `All churches, especially those that receive large amounts of donor-restricted contributions, should consider adopting a gift acceptance policy. Such a policy would include what types of gifts would be received (cash, stock, etc.). It could also include what donor-restricted amounts the church will accept. If the church is never going to buy a bus, for example, there is no reason to accept funds for such a purpose.`,
  `The most obvious way to improve this calculation is to increase contributions without donor restrictions.`,
];

const contrPerAvgAttAndGU_whatDoesThisMean = [
  `The key difference between this result and Measurement 12 is that this is calculated on total contributions (both with and without donor restrictions) and removes the effect of all large one-time gifts.`,
  `When a church is in the midst of a specific campaign, it will likely receive some large one-time gifts. Since this ratio includes both gifts with and without donor restrictions, it is important that these are eliminated; otherwise, there could be large swings between years. As with Measurement 12, the power of this ratio is in analyzing trends in congregational giving habits between years. Keep in mind that during the period of a capital campaign this figure may be inflated even with the removal of large one-time gifts, because of an increase in smaller gifts as well.`,
  `Again, the most apparent way to improve this calculation is to increase total contributions.`,
];

const personnelInclude_whatDoesThisMean = [
  `Many churches have moved to outsourcing certain key functions in their operations (such as custodial, information technology, and accounting functions, to name a few). Outsourcing allows churches to rely on vendors who specialize in a particular field and avoid hiring that expertise in-house, particularly when they don't need that skill on a full-time basis. This also reduces the associated recruiting and operational costs of these functions.`,
  `As many churches turn to outsourcing to take advantage of specialists with expertise and technical equipment, it's important to measure the cost of outsourcing when looking at personnel costs. This ratio incorporates those factors and calculates a fully loaded cost, including outsourced employees. This will allow the church to compare its total personnel cost with peers who may or may not outsource.`,
];

const totalCashExpendExcludePerGU_whatDoesThisMean = [
  `Has your church ever wondered what your cash financial cost per giving unit is? This measure provides the answer. First, it takes total expenses and subtracts out the largest non-cash expense, which is depreciation and amortization. Next, it adds back the largest cash outflow (which is not an expense) or current debt principal. The purpose of this is to approximate total annual cash expenditures for your church. Then it divides that total by the number of giving units.`,
  `The power of this measure is in the peer group comparison. This allows your church to see if your total cash expenditures are high or low compared to your peers. It also shows the increases and decreases to this measure between years.`,
];

const benefitsToSalaries_whatDoesThisMean = [
  `Benefits are important for employees, especially when they may not be paid as competitively as the church would like to be able to pay them. This ratio allows your church to see what percentage of the salary cost benefits are and, more importantly, how that percentage compares to others.`,
  `This makes the peer comparison invaluable, especially in a smaller peer group.`,
];

const benefitsSalariesTotal_whatDoesThisMean = [
  `Many churches have moved to outsourcing certain key functions in their operations (such as custodial, information technology, and accounting functions, to name a few). Outsourcing allows churches to rely on vendors who specialize in a particular field and avoid hiring that expertise in-house, particularly when they don't need that skill on a full-time basis. This also reduces the associated recruiting and operational costs of these functions.`,
  `As many churches turn to outsourcing to take advantage of specialists with expertise and technical equipment, it's important to measure the cost of outsourcing when looking at payroll costs. This ratio incorporates those factors and calculates a fully loaded cost, including outsourced employees. This will allow the church to compare personnel cost per FTE with peers who may or may not outsource.`,
];

const displayDemoComponent = () => {
  const savedData = getStoredData("demoData");
  const parseData = parseStoredData(savedData);

  // console.log('displayDemoComponent hit');
  

  // givingUnits
  createChartFromParsedData(
    parseData,
    "givingUnits_chart",
    "givingUnits_Peer",
    "givingUnits_Client",
    "number",
    0,
    "givingUnits",
    getBenchmarksForField("givingUnits"),
    "Giving Units",
    null // no weighted average
  );
  // givingUnitsToStaff
  createChartFromParsedData(
    parseData,
    "givingUnitsToStaff_chart",
    "givingUnitsToStaff_Peer",
    "givingUnitsToStaff_Client",
    "number",
    0,
    "givingUnitsToStaff",
    getBenchmarksForField("givingUnitsToStaff"),
    "Giving Units to Staff",
    "wa" // use weighted average
  );


  closeSidebarAfterSelectingOption("demo");
};

const displayCashComponent = () => {
  const savedData = getStoredData("cashData");
  const parseData = parseStoredData(savedData);

  // daysExpendableNetAssets
  createChartFromParsedData(
    parseData,
    "daysExpendableNetAssets_chart",
    "daysExpendableNetAssets_Peer",
    "daysExpendableNetAssets_Client",
    "number",
    0,
    "daysExpendableNetAssets",
    getBenchmarksForField("daysExpendableNetAssets"),
    "Days of Expendable Net Asset Reserves",
    "wa" // use weighted average
  );

  // daysOperatingCash
  createChartFromParsedData(
    parseData,
    "daysOperatingCash_chart",
    "daysOperatingCash_Peer",
    "daysOperatingCash_Client",
    "number",
    0,
    "daysOperatingCash",
    getBenchmarksForField("daysOperatingCash"),
    "Days of Operating Cash and Investments on Hand to Fund Annual Cash Expenditures",
    "wa" // use weighted average
  );

  // cashFlowsFromOperatingActivities
  createChartFromParsedData(
    parseData,
    "cashFlowsFromOperatingActivities_chart",
    "cashFlowsFromOperatingActivities_Peer",
    "cashFlowsFromOperatingActivities_Client",
    "dollar",
    0,
    "cashFlowsFromOperatingActivities",
    getBenchmarksForField("cashFlowsFromOperatingActivities"),
    "Cash Flows from Operating Activities",
    null // no weighted average
  );

  // liquidityRatio
  createChartFromParsedData(
    parseData,
    "liquidityRatio_chart",
    "liquidityRatio_Peer",
    "liquidityRatio_Client",
    "number",
    0,
    "liquidityRatio",
    getBenchmarksForField("liquidityRatio"),
    "Liquidity Ratio",
    "wa" // use weighted average
  );

  // netCashAvailability
  createChartFromParsedData(
    parseData,
    "netCashAvailability_chart",
    "netCashAvailability_Peer",
    "netCashAvailability_Client",
    "dollar",
    0,
    "netCashAvailability",
    getBenchmarksForField("netCashAvailability"),
    "Net Cash Availability",
    null // no weighted average
  );

  createBenchmark("Good: > 60 | Warning: 30-60 | Action: < 30", "cashData", "row_daysExpendableNetAssets");
  createBenchmark("Good: > 90 | Warning: 60-90 | Action: < 60", "cashData", "row_daysOperatingCash");
  createBenchmark("Good: > 0 | Warning: 1 year of negative results | Action:  2+ years of negative results", "cashData", "row_cashFlowsFromOperatingActivities");
  createBenchmark("Good: > 2 | Warning: 1-2 | Action: < 1", "cashData", "row_liquidityRatio");
  createBenchmark("Good: > 1 month expenses | Warning: > 0 and < 1 month expenses | Action: < 0", "cashData", "row_netCashAvailability");

  createWhatDoesThisMean(daysExpendable_whatDoesThisMean, "row_daysExpendableNetAssets");
  createWhatDoesThisMean(daysOperatingCash_whatDoesThisMean, "row_daysOperatingCash");
  createWhatDoesThisMean(cashFlowsFromOperatingActivities_whatDoesThisMean, "row_cashFlowsFromOperatingActivities");
  createWhatDoesThisMean(liquidityRatio_whatDoesThisMean, "row_liquidityRatio");
  createWhatDoesThisMean(netCashAvailable_whatDoesThisMean, "row_netCashAvailability");

  // Display benchmarks above Expand Info buttons
  setTimeout(() => {
    displayBenchmarksAboveExpandInfo();
  }, 100);

  closeSidebarAfterSelectingOption("cash");
};

const displayDebtComponent = () => {
  const savedData = getStoredData("debtData");
  const parseData = parseStoredData(savedData);

  // debtToContributionsWithout
  createChartFromParsedData(
    parseData,
    "debtToContributionsWithout_chart",
    "debtToContributionsWithout_Peer",
    "debtToContributionsWithout_Client",
    "number",
    1,
    "debtToContributionsWithout",
    getBenchmarksForField("debtToContributionsWithout"),
    "Debt to Contributions Without",
    "wa" // use weighted average
  );

  // currentRatio
  createChartFromParsedData(
    parseData,
    "currentRatio_chart",
    "currentRatio_Peer",
    "currentRatio_Client",
    "number",
    1,
    "currentRatio",
    getBenchmarksForField("currentRatio"),
    "Current Ratio",
    "wa" // use weighted average
  );

  // mandatoryDebtServiceToContributionsWithout
  createChartFromParsedData(
    parseData,
    "mandatoryDebtServiceToContributionsWithout_chart",
    "mandatoryDebtServiceToContributionsWithout_Peer",
    "mandatoryDebtServiceToContributionsWithout_Client",
    "percent",
    0,
    "mandatoryDebtServiceToContributionsWithout",
    getBenchmarksForField("mandatoryDebtServiceToContributionsWithout"),
    "Mandatory Debt Service to Contributions Without",
    "wa" // use weighted average
  );

  // debtPerGivingUnit
  createChartFromParsedData(
    parseData,
    "debtPerGivingUnit_chart",
    "debtPerGivingUnit_Peer",
    "debtPerGivingUnit_Client",
    "dollar",
    0,
    "debtPerGivingUnit",
    getBenchmarksForField("debtPerGivingUnit"),
    "Debt Per Giving Unit",
    "wa" // use weighted average
  );

  // debtCoverage
  createChartFromParsedData(
    parseData,
    "debtCoverage_chart",
    "debtCoverage_Peer",
    "debtCoverage_Client",
    "num",
    2,
    "debtCoverage",
    getBenchmarksForField("debtCoverage"),
    "Debt Coverage",
    "wa" // use weighted average
  );

  createBenchmark("Good: < 2 | Warning: 2-3 | Action: > 3", "debtData", "row_debtToContributionsWithout");
  createBenchmark("Good: > 2 | Warning: 1-2 | Action: < 1", "debtData", "row_currentRatio");
  createBenchmark("Good: < 20 | Warning: 20-30 | Action: > 30", "debtData", "row_mandatoryDebtServiceToContributionsWithout");
  createBenchmark("Good: < 2x | Warning: 2x - 3x | Action: > 3x contributions w/o donor restrictions", "debtData", "row_debtPerGivingUnit");
  createBenchmark("Good: > 1.25 | Warning: 1 - 1.25 | Action: < 1", "debtData", "row_debtCoverage");

  createWhatDoesThisMean(debtToContributionsWithout_whatDoesThisMean, "row_debtToContributionsWithout");
  createWhatDoesThisMean(currentRatio_whatDoesThisMean, "row_currentRatio");
  createWhatDoesThisMean(mandatoryDebtService_whatDoesThisMean, "row_mandatoryDebtServiceToContributionsWithout");
  createWhatDoesThisMean(debtPerGivingUnit_whatDoesThisMean, "row_debtPerGivingUnit");
  createWhatDoesThisMean(debtCoverage_whatDoesThisMean, "row_debtCoverage");

  // Display benchmarks above Expand Info buttons
  setTimeout(() => {
    displayBenchmarksAboveExpandInfo();
  }, 100);

  closeSidebarAfterSelectingOption("debt");
};

const displayIncomeComponent = () => {
  const savedData = getStoredData("incomeData");
  const parseData = parseStoredData(savedData);

  // netIncomeRatio
  createChartFromParsedData(
    parseData,
    "netIncomeRatio_chart",
    "netIncomeRatio_Peer",
    "netIncomeRatio_Client",
    "percent",
    0,
    "netIncomeRatio",
    getBenchmarksForField("netIncomeRatio"),
    "Net Income Ratio",
    "wa" // use weighted average
  );

  // contributionsWithoutDonorPerGivingUnit
  createChartFromParsedData(
    parseData,
    "contributionsWithoutDonorPerGivingUnit_chart",
    "contributionsWithoutDonorPerGivingUnit_Peer",
    "contributionsWithoutDonorPerGivingUnit_Client",
    "dollar",
    0,
    "contributionsWithoutDonorPerGivingUnit",
    getBenchmarksForField("contributionsWithoutDonorPerGivingUnit"),
    "Contributions Without Donor Per Giving Unit",
    null // no weighted average
  );

  // totalContributionsPerGivingUnit
  createChartFromParsedData(
    parseData,
    "totalContributionsPerGivingUnit_chart",
    "totalContributionsPerGivingUnit_Peer",
    "totalContributionsPerGivingUnit_Client",
    "dollar",
    0,
    "totalContributionsPerGivingUnit",
    getBenchmarksForField("totalContributionsPerGivingUnit"),
    "Total Contributions Per Giving Unit",
    null // no weighted average
  );

  createBenchmark("Good: > 0 | Warning: = 0 | Action: < 0", "incomeData", "row_netIncomeRatio");
  createBenchmark("Good: Improving Trend", "incomeData", "row_netIncomeRatio_twoYrAvg");
  createBenchmark("Good: Improving Trend", "incomeData", "row_contributionsWithoutDonorPerGivingUnit_percentChange");
  createBenchmark("Good: > 4,500 | Warning: 3,000 - 4,500 | Action: < 3,000", "incomeData", "row_totalContributionsPerGivingUnit");
  createBenchmark("Good: Improving Trend", "incomeData", "row_totalContributionsPerGivingUnit_percentChange");
  createBenchmark("Good: > 4 | Warning: 3-4 | Action: < 3", "incomeData", "row_localCounty");

  createWhatDoesThisMean(netIncome_whatDoesThisMean, "row_netIncomeRatio");
  createWhatDoesThisMean(contrWithoutPerAvgAttAndGU_whatDoesThisMean, "row_contributionsWithoutDonorPerGivingUnit");
  createWhatDoesThisMean(contrPerAvgAttAndGU_whatDoesThisMean, "row_totalContributionsPerGivingUnit");

  // Display benchmarks above Expand Info buttons
  setTimeout(() => {
    displayBenchmarksAboveExpandInfo();
  }, 100);

  closeSidebarAfterSelectingOption("income");
};

const displayExpenseComponent = () => {
  const savedData = getStoredData("expenseData");
  const parseData = parseStoredData(savedData);

  // benefitsToSalaries
  createChartFromParsedData(
    parseData,
    "benefitsToSalaries_chart",
    "benefitsToSalaries_Peer",
    "benefitsToSalaries_Client",
    "percent",
    0,
    "benefitsToSalaries",
    null,
    "Benefits to Salaries",
    "wa" // use weighted average
  );

  // salariesBenefitsIncludingOutsourcedEmployees
  createChartFromParsedData(
    parseData,
    "salariesBenefitsIncludingOutsourcedEmployees_chart",
    "salariesBenefitsIncludingOutsourcedEmployees_Peer",
    "salariesBenefitsIncludingOutsourcedEmployees_Client",
    "dollar",
    0,
    "salariesBenefitsIncludingOutsourcedEmployees",
    null,
    "Salaries Benefits Including Outsourced Employees",
    "wa" // use weighted average
  );

  // personnelToCashExpenditure
  createChartFromParsedData(
    parseData,
    "personnelToCashExpenditure_chart",
    "personnelToCashExpenditure_Peer",
    "personnelToCashExpenditure_Client",
    "percent",
    0,
    "personnelToCashExpenditure",
    null,
    "Personnel to Cash Expenditure",
    "wa" // use weighted average
  );

  // cashExpendituresPerGivingUnit
  createChartFromParsedData(
    parseData,
    "cashExpendituresPerGivingUnit_chart",
    "cashExpendituresPerGivingUnit_Peer",
    "cashExpendituresPerGivingUnit_Client",
    "dollar",
    1,
    "cashExpendituresPerGivingUnit",
    null,
    "Cash Expenditures Per Giving Unit",
    "wa" // use weighted average
  );

  createBenchmark("", "expenseData", "row_benefitsToSalaries");
  createBenchmark("", "expenseData", "row_salariesBenefitsIncludingOutsourcedEmployees");
  createBenchmark("Good: 40-55 | Warning: 35-40 or 55-59 | Action: < 35 or > 59", "expenseData", "row_personnelToCashExpenditure");
  createBenchmark("Good: < 15 | Warning: 15-19 | Action: > 19", "expenseData", "row_mandatoryDebtServiceToCashExpenditure");
  createBenchmark("Good: 40-55 | Warning: 35-40 or 55-59 | Action: < 35 or > 59", "expenseData", "row_personnelIncludingToTotalCashExpenditures");
  createBenchmark("Good: > 10 | Warning: 5-10 | Action: < 5", "expenseData", "row_totalGlobalAndLocalOutreachExpenses");
  createBenchmark("", "expenseData", "row_cashExpendituresPerGivingUnit");

  createWhatDoesThisMean(benefitsToSalaries_whatDoesThisMean, "row_benefitsToSalaries");
  createWhatDoesThisMean(benefitsSalariesTotal_whatDoesThisMean, "row_salariesBenefitsIncludingOutsourcedEmployees");
  createWhatDoesThisMean(personnelInclude_whatDoesThisMean, "row_personnelToCashExpenditure");
  createWhatDoesThisMean(mandatoryDebtService_whatDoesThisMean, "row_mandatoryDebtServiceToCashExpenditure");
  createWhatDoesThisMean(personnelInclude_whatDoesThisMean, "row_personnelIncludingToTotalCashExpenditures");
  createWhatDoesThisMean(totalCashExpendExcludePerGU_whatDoesThisMean, "row_cashExpendituresPerGivingUnit");

  // Removed facility expense and cost per square foot ratios per todo

  // Display benchmarks above Expand Info buttons
  setTimeout(() => {
    displayBenchmarksAboveExpandInfo();
  }, 100);

  closeSidebarAfterSelectingOption("expense");
};

/**
 * Map of field names to their benchmark text for display above Expand Info buttons
 * @type {Object<string, string>}
 */
const fieldBenchmarkMap = {
  daysExpendableNetAssets: "Good: > 60 | Warning: 30-60 | Action: < 30",
  daysOperatingCash: "Good: > 90 | Warning: 60-90 | Action: < 60",
  cashFlowsFromOperatingActivities: "Good: > 0 | Warning: 1 year of negative results | Action:  2+ years of negative results",
  liquidityRatio: "Good: > 2 | Warning: 1-2 | Action: < 1",
  netCashAvailability: "Good: > 1 month expenses | Warning: > 0 and < 1 month expenses | Action: < 0",
  debtToContributionsWithout: "Good: < 2 | Warning: 2-3 | Action: > 3",
  currentRatio: "Good: > 2 | Warning: 1-2 | Action: < 1",
  mandatoryDebtServiceToContributionsWithout: "Good: < 20 | Warning: 20-30 | Action: > 30",
  debtPerGivingUnit: "Good: < 2x | Warning: 2x - 3x | Action: > 3x contributions w/o donor restrictions",
  debtCoverage: "Good: > 1.25 | Warning: 1 - 1.25 | Action: < 1",
  netIncomeRatio: "Good: > 0 | Warning: = 0 | Action: < 0",
  contributionsWithoutDonorPerGivingUnit: "", // No benchmark text
  totalContributionsPerGivingUnit: "Good: > 4,500 | Warning: 3,000 - 4,500 | Action: < 3,000",
  benefitsToSalaries: "", // No benchmark text
  salariesBenefitsIncludingOutsourcedEmployees: "", // No benchmark text
  personnelToCashExpenditure: "Good: 40-55 | Warning: 35-40 or 55-59 | Action: < 35 or > 59",
  cashExpendituresPerGivingUnit: "", // No benchmark text
};

/**
 * Display benchmark text above the Expand Info button for charts that have benchmarks
 * This function should be called after charts are displayed
 * Ensures "Expand Info" button is always aligned to the right, even when no benchmark text exists
 */
const displayBenchmarksAboveExpandInfo = () => {
  // Find ALL Expand Info buttons (those with data-modal-target ending in "_modal")
  const allExpandInfoButtons = document.querySelectorAll(
    'button[data-modal-target$="_modal"]'
  );

  allExpandInfoButtons.forEach((button) => {
    // Extract field name from modal target (e.g., "givingUnits_modal" -> "givingUnits")
    const modalTarget = button.getAttribute("data-modal-target");
    if (!modalTarget || !modalTarget.endsWith("_modal")) {
      return;
    }

    const fieldName = modalTarget.replace("_modal", "");

    // Skip non-chart modals (like options_modal, print_modal)
    if (fieldName === "options" || fieldName === "print") {
      return;
    }

    // Get benchmark text from map (undefined if not in map)
    const benchmarkText = fieldBenchmarkMap[fieldName];

    // Find the parent container with the flex layout (match by border-t class)
    let flexContainer = button.parentElement;
    while (flexContainer && !flexContainer.classList.contains("border-t")) {
      flexContainer = flexContainer.parentElement;
    }

    if (!flexContainer) {
      // console.warn(`Flex container not found for ${fieldName}`);
      return;
    }

    // Find the flex-shrink-0 div that contains the button
    const buttonContainer = button.closest(".flex-shrink-0");

    if (!buttonContainer) {
      // console.warn(`Button container not found for ${fieldName}`);
      return;
    }

    // Check if benchmark text already exists
    const existingBenchmark = flexContainer.querySelector(
      `[data-benchmark-field="${fieldName}"]`
    );

    // Handle benchmark text
    if (benchmarkText && benchmarkText.trim() !== "") {
      // We have benchmark text to display
      if (existingBenchmark) {
        // Update existing benchmark text
        existingBenchmark.textContent = benchmarkText;
      } else {
        // Create the paragraph element with benchmark text
        const benchmarkP = document.createElement("p");
        benchmarkP.className =
          "mb-2 text-sm font-medium text-gray-500 dark:text-white";
        benchmarkP.textContent = benchmarkText;
        benchmarkP.setAttribute("data-benchmark-field", fieldName);

        // Insert the benchmark text as a sibling before the button container
        buttonContainer.parentNode.insertBefore(benchmarkP, buttonContainer);
      }
      
      // Remove ml-auto from button container if it exists (benchmark text will push it right via justify-between)
      if (buttonContainer.classList.contains("ml-auto")) {
        buttonContainer.classList.remove("ml-auto");
      }
    } else {
      // No benchmark text - ensure button is pushed to the right
      if (existingBenchmark) {
        // Remove existing empty benchmark text
        existingBenchmark.remove();
      }
      
      // Add ml-auto to button container to push it to the right when no benchmark text exists
      if (!buttonContainer.classList.contains("ml-auto")) {
        buttonContainer.classList.add("ml-auto");
      }
    }
  });
};
