/**
 * Fix Unicode encoding issues in content, particularly apostrophes
 * @param {string} content - The content string to fix
 * @returns {string} - Content with properly encoded Unicode characters
 */
function fixUnicodeCharacters(content) {
  if (typeof content !== 'string') {
    return content;
  }

  // Replace common problematic Unicode characters that display as �
  const unicodeReplacements = {
    // Apostrophe variations that often cause encoding issues
    '\u2019': "'",     // Right single quotation mark (smart apostrophe)
    '\u2018': "'",     // Left single quotation mark  
    '\u00B4': "'",     // Acute accent
    '\u0060': "'",     // Grave accent
    '\u02BC': "'",     // Modifier letter apostrophe
    
    // Quote variations
    '\u201C': '"',     // Left double quotation mark
    '\u201D': '"',     // Right double quotation mark
    '\u201E': '"',     // Double low-9 quotation mark
    '\u201F': '"',     // Double high-reversed-9 quotation mark
    
    // Dash variations
    '\u2013': '-',     // En dash
    '\u2014': '--',    // Em dash
    '\u2015': '--',    // Horizontal bar
    
    // Other common problematic characters
    '\u2026': '...',   // Horizontal ellipsis
    '\u00A0': ' ',     // Non-breaking space
    '\uFFFD': "'",     // Unicode replacement character (often appears as �)
  };

  let fixedContent = content;

  // Apply each replacement
  Object.entries(unicodeReplacements).forEach(([problematic, replacement]) => {
    fixedContent = fixedContent.replace(new RegExp(problematic, 'g'), replacement);
  });

  // Additional cleanup for any remaining � characters that might be malformed apostrophes
  fixedContent = fixedContent.replace(/\uFFFD/g, "'");

  return fixedContent;
}

// Define "What Does This Mean" content arrays from todo_nov18_25.md
const daysExpendable_whatDoesThisMean = [
  `This ratio tells how many days of operating expenses are available in net asset reserves. The difference between this and Ratio 2 is that this ratio uses net asset reserves, which take into account the accrual of current assets and current liabilities. `,
  `The term expendable net assets represents the total resources available to spend on operations, excluding future gifts made or revenues generated by the church. Think of it as how long you could live on a savings account. `,
  `Expendable net assets consist of net assets without donor restrictions, undesignated (formerly referred to as unrestricted, undesignated net assets), which are net assets that result from achieving positive net income year after year in the without donor restrictions column of the statement of activities. This is the result of spending fewer contributions without donor restrictions than were taken in, or of the positive operations of other ministries within the church, such as a bookstore or a media ministry. The total of positive operations from these revenue sources (after expenses) produces undesignated net assets without donor restrictions. The balance also includes reserves designated by the board for specific operating purposes other than capital expenditures, but excludes reserves that represent the church's equity in land, buildings, and equipment (NIFA).`,
  `The total of the amounts in the numerator is divided by total expenditures less the annual non-cash expense of depreciation. The net result of removing depreciation is to calculate, based on prior expenditures, the cash expenses your church would incur. `,
  `The number of days can be temporarily high if the church has recorded large gifts without donor restrictions that have not been spent at year-end. This is the case for churches with fiscal years ending on December 31, when many attendees give large year-end gifts in order to meet tax-reporting deadlines. The number of days can also appear low if the church incurred a large one-time expenditure that won't be repeated in the future.`,
  `To improve this ratio over the long term, it is necessary to increase undesignated net assets without donor restrictions or board-designated net assets for operations, or both. Achieving positive net income in the without donor restrictions column of the statement of activities year after year accomplishes this. Growth of the undesignated net assets without donor restrictions must exceed the rate of increase in the denominator or cash expenses to positively improve this ratio. Conversely, keeping expendable net asset reserves the same but cutting cash expenses will also have a positive impact on this ratio.`,
];

const daysOperatingCash_whatDoesThisMean = [
  `This ratio calculates the days operating cash and investments on hand to fund annual cash expenditures, but specifically related to very liquid assets. It only considers operating cash and investments, not other current assets and liabilities.`,
  `Operating cash and investments are those resources that do not carry donor restrictions on the assets and are available for the church to spend without restrictions. This number is divided by the sum of expenses plus capitalized interest, which is interest paid in cash but not expensed by the church. This may occur during periods of construction when GAAP requires the church to capitalize this cash expense as part of the cost of the asset being built. Depreciation is also removed because it represents a significant non-cash annual expense recorded by the church. Current debt principal is added back because it represents cash spent, but it is not recorded as an expense in the financial statements. The net effect of these adjustments is to estimate, based on prior expenditures, the annual cash expenditures the church would incur.`,
  `To improve this ratio, operating cash or investments must increase at a rate greater than the denominator (annual cash expenditures). Conversely, keeping operating cash or investments the same but cutting annual cash expenditures will also have a positive impact on this ratio. `,
];

const liquidityRatio_whatDoesThisMean = [
  `This ratio measures how operating cash and investments are able to cover current operating liabilities. These operating liabilities exclude  current building fund liabilities, which  normally have a separate source of cash from restricted revenues or budgets. It also excludes any amounts owed on a short-term construction line of credit. These are typically interest-only until converted into a long-term debt and paid over time, and do not require payment from operating cash or investments in the short-term. It also excludes deferred revenues, which do not require an outlay of cash. `,
  `This ratio will tell the reader how many times actual operating liabilities can be funded from operating reserves. To improve this ratio, either operating cash or investments must improve at a rate greater than operating liabilities. Conversely, operating liabilities must either decrease while the operating cash and investments remain consistent or decrease at a lesser rate. `,
];

const netCashAvailable_whatDoesThisMean = [
  `This measurement calculates the amount of cash available for other uses after the church has satisfied its adjusted current liabilities (excluding amounts borrowed on a construction line of credit) and cash and investments set aside for projects with donor restrictions (excluding non-cash amounts or pledges receivable from donor-restricted projects) resulting from gifts given by donors who have placed restrictions on their use. Amounts borrowed on a construction line of credit are also excluded, as they will ultimately be refinanced with the debt and paid over time.`,
  `This may be one of the most important measures provided to your church leadership. Many churches today find that senior management (pastoral staff) and the governing board want to know how much cash the church has. The most important question is not "How much do we have?" but rather, "Whose cash is it and how much of it can we spend?" Those are typically two very different answers.`,
  `A net cash availability number factors in the cash required for the immediate future (less than 10 days) to determine what can safely be spent`,
  `Net assets with donor restrictions are not to be expended for general operating purposes and therefore are excluded from the cash balance. Keep in mind that the portion of net assets with donor restrictions that are supported by pledges receivable are excluded (deducted from total netassets with donor restrictions) as they would have no impact on this cash-based calculation. Some churches have in essence "borrowed" from reserves with donor restrictions because they overspent in operations. This calculation will help management identify if this is happening in your church, so it is crucial to provide this information to decision makers.`,
  `To improve this figure, you must change one or a combination of the following factors:<ul><li>Increase operating cash or investments</li><li>Decrease current liabilities </li><li>Decrease operational net assets with donor  restrictions</li></ul>`,
];

const debtToContributionsWithout_whatDoesThisMean = [
  `This ratio measures how many times debt is greater than annual contributions without donor restrictions, which are the primary income source for most churches.`,
  `Lenders look at debt as funded by contributions without donor restrictions because those are the resources from which the church will be able to pay mandatory debt service payments. By looking at trends in various congregations, contributions without donor restrictions help the lender determine what debt load the church will be able to handle on top of other required expenditures (salaries, benefits, mission expenses, facility expenses, etc.).`,
  `The best way to improve this ratio is to decrease total debt. Another option is to increase contributions without donor restrictions. However, forecasting an increased revenue source is less certain than a careful plan that intentionally lowers the debt balance.`,
];

const currentRatio_whatDoesThisMean = [
  `This ratio helps determine how easily the church can meet its current obligations through current assets.`,
  `There are differences of opinion as to what the ratio results should be. A ratio of less than 1.0 could be interpreted as a <strong class="red">red flag</strong> that the church does not have enough in current assets to pay its upcoming liabilities. This could result in the need to borrow from restricted funds or the need to obtain a temporary line of credit to cover short-term obligations. Results this low would also warrant a careful review of the cash flow and reserves ratios and measurements. Your church will need to be aware of this and monitor the ratio on an ongoing basis to avoid being surprised by a cash shortage.`,
  `To improve this ratio, increase current assets at a rate greater than current liabilities. Conversely, your church may decide to pay down current liabilities, but these are usually paid with current assets. The key to improving the ratio is to lower current assets less than current liabilities.`,
];

const mandatoryDebtService_whatDoesThisMean = [
  `This ratio pertains more to the debt service (debt payment requirements), and looks at the percentage of contributions that will be used to make annual debt service payments.`,
  `Although a church may have many revenue sources, lenders typically only consider contributions without donor restrictions when determining how much debt a church can manage.`,
  `To improve this ratio, the church must lower its required annual debt principal and interest payments. Modifying the terms of the debt with the lender should accomplish this. (Note that this may violate the debt covenant and require a bank covenant waiver and payment of related fees.) You can also improve the ratio by maintaining the same debt service payment schedule while increasing contributions without donor restrictions. Obviously, increasing a revenue source carries its own unique challenges.`,
];

const debtPerGivingUnit_whatDoesThisMean = [
  `This measure introduces the concept of a giving unit.  A giving unit is usually a group of family members who contribute jointly to the church. A giving unit is also defined as any recurring supporter of the ministry. This excludes the individual who may make a smaller one-time gift supporting an event, such as a short-term mission trip. To identify only the regular recurring giving units, the measure only includes giving units that contribute more than $250 annually to the church.`,
  `This figure is calculated by dividing total debt by adult attendees and giving units. It will vary significantly based on the philosophy, denomination, location, age, size, and demographics of the church. Each church will need to determine the level of debt it is comfortable maintaining or servicing. You will probably encounter varying opinions within your congregation. Some individuals believe that a church should not incur debt while others are very comfortable with a high debt load.`,
  `Lenders believe that debt will be funded by contributions without donor restrictions because typically these are the resources from which the church will be able to pay mandatory debt service payments.`,
];

const debtCoverage_whatDoesThisMean = [
  `This ratio is used to determine how many times a church would be able to cover its current annual debt obligations from current operations. This is a very common debt covenant ratio used by lenders to monitor the ability of a church to make annual debt service payments. The results could change dramatically between years based on swings to the change in net assets without donor restrictions. For example, if a church used its reserves to perform more repairs and maintenance to its facility than normal, the increase in expense could cause a much lower positive or even negative change in net assets without donor restrictions. This would adversely affect the ratio and could unexpectedly violate a debt covenant, potentially requiring the church to obtain a bank covenant waiver and pay related fees. The benchmark agreed to by the lender is a key negotiation point, especially with a new lender. It may also factor into the amount of reserves the church leadership deems necessary.`,
  `The change in net assets without donor restrictions is primarily driven by operational decisions that affect things such as the management of budgeted expenses. Successes or failures at developing good stewardship habits in the congregation, resulting in growth or decline of contributions without donor restrictions, can also have a significant effect on this number. Interest expense represents interest payments under the terms of the note.`,
  `The biggest factor impacting this ratio is significant increases or decreases to the change in net assets without donor restrictions. Ministry decisions or necessary additional expenditures as discussed above may drive the decision to spend net assets without donor restrictions and result in lower positive or negative change in net assets without donor restrictions. While a lower positive or negative change in net assets without donor restrictions may impact this ratio in the current year, it is important to look at the trends and understand the reasons behind ministry decisions to spend resources without donor restrictions. It is also equally important that the effect of these decisions on the ratio is not a last-minute surprise to management or the outside lender. An unexpected result could cause a strain on the relationship with the lender.`,
  `Lowering required annual debt principal and interest payments may also modify the denominator. This is usually done by modifying the terms of the debt with the lender, which may violate the debt covenant. Lower interest expense will also affect the numerator positively. So, increasing change in net assets without donor restrictions is still the best way to improve this ratio.`,
];

const netIncome_whatDoesThisMean = [
  `The purpose of this ratio is to show if the results of the church's general operations are positive or negative, and by how much. In business terms, this shows if the church is making or losing money in its basic day-to-day function of ministering to the local community. The importance of this ratio is immediately apparent. If a church is losing money in its basic operations over time, eventually it will no longer be viable and will have to close. At some point this church will reach the stage where it is either too late to make the necessary operational changes or it no longer has the funds or the confidence to make them. That point is more easily identified in retrospect, but the net income ratio can provide a bellwether to warn of impending financial distress.`,
  `The change in net assets without donor restrictions (net income or net loss) is a measure of operational results for management. The change in net assets without donor restrictions more closely explains whether management met the anticipated targets for spending or not. The net income ratio defines what percentage of revenues without donor restrictions resulted in the net income. Another way of viewing this ratio is to ask what percentage of revenues was spent during the year.`,
  `One factor to consider when calculating this ratio is that very large one-time events, such as the receipt of a large one-time gift without donor restrictions made at the end of the fiscal year, can significantly influence a church's net income without donor restrictions.`,
  `Your church may not want to have large surpluses every year. You may want to make sure that money is invested in the ministries of the church. However, you need to make sure some reserves are in place. Monitoring this ratio and the trend of it from year to year will help determine the financial health of your church.`,
  `For example, a church may build reserves for a few years to launch a new ministry or a satellite campus. Then for a year or two there will be significant net losses as that ministry begins operating. If the positive years had not happened first, the ministry launch may not have been possible.`,
  `Surpluses with a couple of years of "investment" followed by a stabilization of income will show how the surpluses and deficits averaged over that period.`,
  `Increasing the change in net assets without donor restrictions will have the single most positive impact on this ratio. As discussed previously, there are many ministry reasons a church may or may not choose to show consistent surpluses. It is because of these reasons that the ratio is also calculated using the average net income over several years, to determine if recent deficits are a one-time issue or a growing, unchecked trend.`,
];

const contrWithoutPerAvgAttAndGU_whatDoesThisMean = [
  `This calculation, which removes the effect of large one-time (unusual) gifts without donor restrictions, can be compared from year to year to see the trends and determine the impact on the church and budget. Another valuable comparison is to calculate what contributions would be if every giving unit made a certain amount (i.e., $50,000 a year) and tithed on that amount. The church could use this measurement to make the congregation aware of what the current giving per adult attendee and giving unit is, and what the projected giving would be if everyone participated.`,
  `Churches today have to look at contributions differently than at any time in the past. Contributions are down, and generational differences are very strong even in the way people contribute to their church. Young people, who are more cause-driven, tend to give to specific purposes and causes and are less interested in giving to general operations. This creates budgeting concerns.`,
  `Churches choose to communicate these needs in various ways. Some list them in the bulletin. Some annually communicate contributions per adult attendee or giving unit. Others may request contributions towards a specific need and tell the congregation what was received and how the funds were spent, and show pictures of the repairs or replacements.`,
  `All churches, especially those that receive large amounts of donor-restricted contributions, should consider adopting a <a href="https://capincrouse.com/elements-well-drafted-gift-acceptance-policy/" target="_blank">gift acceptance policy</a>. Such a policy would include what types of gifts would be received (cash, stock, etc.). It could also include what donor-restricted amounts the church will accept. If the church is never going to buy a bus, for example, there is no reason to accept funds for such a purpose.`,
  `The most obvious way to improve this calculation is to increase contributions without donor restrictions.`,
];

const contrPerAvgAttAndGU_whatDoesThisMean = [
  `The key difference between this result and Measurement 12 is that this is calculated on total contributions (both with and without donor restrictions) and removes the effect of pledges, which are essentially a non-cash accrual, and all large one-time gifts.`,
  `When a church is in the midst of a specific campaign, it will likely receive some large one-time gifts. Since this ratio includes both gifts with and without donor restrictions, it is important that these are eliminated; otherwise, there could be large swings between years. As with Measurement 12, the power of this ratio is in analyzing trends in congregational giving habits between years. Keep in mind that during the period of a capital campaign this figure may be inflated even with the removal of large one-time gifts, because of an increase in smaller gifts as well.`,
  `Again, the most apparent way to improve this calculation is to increase total contributions.`,
];

const personnelInclude_whatDoesThisMean = [
  `Salaries and benefits, interest, and debt service payments (which are not an expense but rather a reduction of a liability) represent the majority of resource outflows from the local church.`,
  `Therefore, it is essential to continually monitor these levels as a percentage of total cash expenditures. It is also important to promptly follow up on changes in trends or unusual variances from peers to ensure that your ministry resources are continually maximized.`,
  `This ratio allows your church to look at two of its largest cash outflows and determine the portion of the operating budget that will be used. Often a growth cycle results in an amount of debt the church anticipates being able to pay off as more people are able and encouraged to attend. However, the church needs to be able to pay the bills and provide the services that will attract new people with the current budget. Reviewing this ratio in advance of any major debt decisions will help you analyze the feasibility of your facility expansion goals.`
];

const totalCashExpendExcludePerGU_whatDoesThisMean = [
  `Has your church ever wondered what your cash financial cost per adult attendee and giving unit is? This measure provides the answer. First, it takes total expenses and subtracts out the largest non-cash expense, which is depreciation. Next, it adds back the largest cash outflow (which is not an expense) or current debt principal. The purpose of this is to approximate total annual cash expenditures for your church. Then it divides that total by the adult attendees or giving units.`,
  `The power of this measure is in the peer group comparison. This allows your church to see if your total cash expenditures are high or low compared to your peers. It also shows the increases and decreases to this measure between years.`,
];

const benefitsToSalaries_whatDoesThisMean = [
  `Benefits are important for employees, especially when they may not be paid as competitively as the church would like to be able to pay them. This ratio allows your church to see what percentage of the salary cost benefits are and, more importantly, how that percentage compares to others.`,
  `This makes the peer comparison invaluable, especially in a smaller peer group.`,
];

const benefitsSalariesTotal_whatDoesThisMean = [
  `Monitoring salaries and benefits per FTE over time will help your church determine the competitiveness of salaries and benefits and monitor changes in salary and benefit costs to the church.`,
  `<a href="https://ministrypay.com/" target="_blank">ministrypay.com</a>  <a href="http://churchlawandtax.com/" target="_blank">churchlawandtax.com,</a>   <a href="http://leadnet.org/salary" target="_blank">http://leadnet.org/salary</a>`,
];

const displayDemoComponent = () => {
  const savedData = getStoredData("demoData");
  const parseData = parseStoredData(savedData);

  // console.log('displayDemoComponent hit');
  

  // givingUnits
  createChartFromParsedData(
    parseData,
    "givingUnits_chart",
    "givingUnits_Peer",
    "givingUnits_Client",
    "number",
    0,
    "givingUnits",
    getBenchmarksForField("givingUnits"),
    "Giving Units",
    null // no weighted average
  );
  // givingUnitsToStaff
  createChartFromParsedData(
    parseData,
    "givingUnitsToStaff_chart",
    "givingUnitsToStaff_Peer",
    "givingUnitsToStaff_Client",
    "number",
    0,
    "givingUnitsToStaff",
    getBenchmarksForField("givingUnitsToStaff"),
    "Giving Units to Staff",
    "wa" // use weighted average
  );


  closeSidebarAfterSelectingOption("demo");
};

const displayCashComponent = () => {
  const savedData = getStoredData("cashData");
  const parseData = parseStoredData(savedData);

  // daysExpendableNetAssets
  createChartFromParsedData(
    parseData,
    "daysExpendableNetAssets_chart",
    "daysExpendableNetAssets_Peer",
    "daysExpendableNetAssets_Client",
    "number",
    0,
    "daysExpendableNetAssets",
    getBenchmarksForField("daysExpendableNetAssets"),
    "Days Expendable Net Assets",
    "wa" // use weighted average
  );

  // daysOperatingCash
  createChartFromParsedData(
    parseData,
    "daysOperatingCash_chart",
    "daysOperatingCash_Peer",
    "daysOperatingCash_Client",
    "number",
    0,
    "daysOperatingCash",
    getBenchmarksForField("daysOperatingCash"),
    "Days Operating Cash",
    "wa" // use weighted average
  );

  // cashFlowsFromOperatingActivities
  createChartFromParsedData(
    parseData,
    "cashFlowsFromOperatingActivities_chart",
    "cashFlowsFromOperatingActivities_Peer",
    "cashFlowsFromOperatingActivities_Client",
    "dollar",
    0,
    "cashFlowsFromOperatingActivities",
    getBenchmarksForField("cashFlowsFromOperatingActivities"),
    "Cash Flows from Operating Activities",
    null // no weighted average
  );

  // liquidityRatio
  createChartFromParsedData(
    parseData,
    "liquidityRatio_chart",
    "liquidityRatio_Peer",
    "liquidityRatio_Client",
    "number",
    0,
    "liquidityRatio",
    getBenchmarksForField("liquidityRatio"),
    "Liquidity Ratio",
    "wa" // use weighted average
  );

  // netCashAvailability
  createChartFromParsedData(
    parseData,
    "netCashAvailability_chart",
    "netCashAvailability_Peer",
    "netCashAvailability_Client",
    "dollar",
    0,
    "netCashAvailability",
    getBenchmarksForField("netCashAvailability"),
    "Net Cash Availability",
    null // no weighted average
  );

  createBenchmark("Good: > 60 | Warning: 30-60 | Action: < 30", "cashData", "row_daysExpendableNetAssets");
  createBenchmark("Good: > 90 | Warning: 60-90 | Action: < 60", "cashData", "row_daysOperatingCash");
  createBenchmark("Good: > 0 | Warning: 1 year of negative results  Action:  2+ years of negative results", "cashData", "row_cashFlowsFromOperatingActivities");
  createBenchmark("Good: > 4 | Warning: 1-4 | Action: < 1", "cashData", "row_liquidityRatio");
  createBenchmark("Good: > 1 month expenses  Warning: > 0 and < 1 month expenses | Action: < 0", "cashData", "row_netCashAvailability");

  createWhatDoesThisMean(daysExpendable_whatDoesThisMean, "row_daysExpendableNetAssets");
  createWhatDoesThisMean(daysOperatingCash_whatDoesThisMean, "row_daysOperatingCash");
  createWhatDoesThisMean([], "row_cashFlowsFromOperatingActivities");
  createWhatDoesThisMean(liquidityRatio_whatDoesThisMean, "row_liquidityRatio");
  createWhatDoesThisMean(netCashAvailable_whatDoesThisMean, "row_netCashAvailability");

  closeSidebarAfterSelectingOption("cash");
};

const displayDebtComponent = () => {
  const savedData = getStoredData("debtData");
  const parseData = parseStoredData(savedData);

  // debtToContributionsWithout
  createChartFromParsedData(
    parseData,
    "debtToContributionsWithout_chart",
    "debtToContributionsWithout_Peer",
    "debtToContributionsWithout_Client",
    "number",
    1,
    "debtToContributionsWithout",
    getBenchmarksForField("debtToContributionsWithout"),
    "Debt to Contributions Without",
    "wa" // use weighted average
  );

  // currentRatio
  createChartFromParsedData(
    parseData,
    "currentRatio_chart",
    "currentRatio_Peer",
    "currentRatio_Client",
    "number",
    1,
    "currentRatio",
    getBenchmarksForField("currentRatio"),
    "Current Ratio",
    "wa" // use weighted average
  );

  // mandatoryDebtServiceToContributionsWithout
  createChartFromParsedData(
    parseData,
    "mandatoryDebtServiceToContributionsWithout_chart",
    "mandatoryDebtServiceToContributionsWithout_Peer",
    "mandatoryDebtServiceToContributionsWithout_Client",
    "percent",
    0,
    "mandatoryDebtServiceToContributionsWithout",
    getBenchmarksForField("mandatoryDebtServiceToContributionsWithout"),
    "Mandatory Debt Service to Contributions Without",
    "wa" // use weighted average
  );

  // debtPerGivingUnit
  createChartFromParsedData(
    parseData,
    "debtPerGivingUnit_chart",
    "debtPerGivingUnit_Peer",
    "debtPerGivingUnit_Client",
    "dollar",
    0,
    "debtPerGivingUnit",
    getBenchmarksForField("debtPerGivingUnit"),
    "Debt Per Giving Unit",
    "wa" // use weighted average
  );

  // debtCoverage
  createChartFromParsedData(
    parseData,
    "debtCoverage_chart",
    "debtCoverage_Peer",
    "debtCoverage_Client",
    "num",
    2,
    "debtCoverage",
    getBenchmarksForField("debtCoverage"),
    "Debt Coverage",
    "wa" // use weighted average
  );

  createBenchmark("Good: < 2 | Warning: 2-3 | Action: > 3", "debtData", "row_debtToContributionsWithout");
  createBenchmark("Good: > 2 | Warning: 1-2 | Action: < 1", "debtData", "row_currentRatio");
  createBenchmark("Good: < 15 | Warning: 15-20 | Action: > 20", "debtData", "row_mandatoryDebtServiceToContributionsWithout");
  createBenchmark("Good: < 2x | Warning: 2x - 3x | Action: > 3x contributions w/o donor restrictions", "debtData", "row_debtPerGivingUnit");
  createBenchmark("Good: > 1.25 | Warning: 1 - 1.25 | Action: < 1", "debtData", "row_debtCoverage");

  createWhatDoesThisMean(debtToContributionsWithout_whatDoesThisMean, "row_debtToContributionsWithout");
  createWhatDoesThisMean(currentRatio_whatDoesThisMean, "row_currentRatio");
  createWhatDoesThisMean(mandatoryDebtService_whatDoesThisMean, "row_mandatoryDebtServiceToContributionsWithout");
  createWhatDoesThisMean(debtPerGivingUnit_whatDoesThisMean, "row_debtPerGivingUnit");
  createWhatDoesThisMean(debtCoverage_whatDoesThisMean, "row_debtCoverage");

  closeSidebarAfterSelectingOption("debt");
};

const displayIncomeComponent = () => {
  const savedData = getStoredData("incomeData");
  const parseData = parseStoredData(savedData);

  // netIncomeRatio
  createChartFromParsedData(
    parseData,
    "netIncomeRatio_chart",
    "netIncomeRatio_Peer",
    "netIncomeRatio_Client",
    "percent",
    1,
    "netIncomeRatio",
    getBenchmarksForField("netIncomeRatio"),
    "Net Income Ratio",
    "wa" // use weighted average
  );

  // contributionsWithoutDonorPerGivingUnit
  createChartFromParsedData(
    parseData,
    "contributionsWithoutDonorPerGivingUnit_chart",
    "contributionsWithoutDonorPerGivingUnit_Peer",
    "contributionsWithoutDonorPerGivingUnit_Client",
    "dollar",
    1,
    "contributionsWithoutDonorPerGivingUnit",
    getBenchmarksForField("contributionsWithoutDonorPerGivingUnit"),
    "Contributions Without Donor Per Giving Unit",
    null // no weighted average
  );

  // totalContributionsPerGivingUnit
  createChartFromParsedData(
    parseData,
    "totalContributionsPerGivingUnit_chart",
    "totalContributionsPerGivingUnit_Peer",
    "totalContributionsPerGivingUnit_Client",
    "dollar",
    1,
    "totalContributionsPerGivingUnit",
    getBenchmarksForField("totalContributionsPerGivingUnit"),
    "Total Contributions Per Giving Unit",
    null // no weighted average
  );

  createBenchmark("Good: > 0 | Warning: = 0 | Action: < 0", "incomeData", "row_netIncomeRatio");
  createBenchmark("Good: Improving Trend", "incomeData", "row_netIncomeRatio_twoYrAvg");
  createBenchmark("Good: Improving Trend", "incomeData", "row_contributionsWithoutDonorPerGivingUnit_percentChange");
  createBenchmark("Good: > 4,500 | Warning: 3,000 - 4,500 | Action: < 3,000", "incomeData", "row_totalContributionsPerGivingUnit");
  createBenchmark("Good: Improving Trend", "incomeData", "row_totalContributionsPerGivingUnit_percentChange");
  createBenchmark("Good: > 4 | Warning: 3-4 | Action: < 3", "incomeData", "row_localCounty");

  createWhatDoesThisMean(netIncome_whatDoesThisMean, "row_netIncomeRatio");
  createWhatDoesThisMean(contrWithoutPerAvgAttAndGU_whatDoesThisMean, "row_contributionsWithoutDonorPerGivingUnit");
  createWhatDoesThisMean(contrPerAvgAttAndGU_whatDoesThisMean, "row_totalContributionsPerGivingUnit");

  closeSidebarAfterSelectingOption("income");
};

const displayExpenseComponent = () => {
  const savedData = getStoredData("expenseData");
  const parseData = parseStoredData(savedData);

  // benefitsToSalaries
  createChartFromParsedData(
    parseData,
    "benefitsToSalaries_chart",
    "benefitsToSalaries_Peer",
    "benefitsToSalaries_Client",
    "percent",
    0,
    "benefitsToSalaries",
    null,
    "Benefits to Salaries",
    "wa" // use weighted average
  );

  // salariesBenefitsIncludingOutsourcedEmployees
  createChartFromParsedData(
    parseData,
    "salariesBenefitsIncludingOutsourcedEmployees_chart",
    "salariesBenefitsIncludingOutsourcedEmployees_Peer",
    "salariesBenefitsIncludingOutsourcedEmployees_Client",
    "dollar",
    0,
    "salariesBenefitsIncludingOutsourcedEmployees",
    null,
    "Salaries Benefits Including Outsourced Employees",
    "wa" // use weighted average
  );

  // personnelToCashExpenditure
  createChartFromParsedData(
    parseData,
    "personnelToCashExpenditure_chart",
    "personnelToCashExpenditure_Peer",
    "personnelToCashExpenditure_Client",
    "percent",
    0,
    "personnelToCashExpenditure",
    null,
    "Personnel to Cash Expenditure",
    "wa" // use weighted average
  );

  // cashExpendituresPerGivingUnit
  createChartFromParsedData(
    parseData,
    "cashExpendituresPerGivingUnit_chart",
    "cashExpendituresPerGivingUnit_Peer",
    "cashExpendituresPerGivingUnit_Client",
    "dollar",
    1,
    "cashExpendituresPerGivingUnit",
    null,
    "Cash Expenditures Per Giving Unit",
    "wa" // use weighted average
  );

  createBenchmark("", "expenseData", "row_benefitsToSalaries");
  createBenchmark("", "expenseData", "row_salariesBenefitsIncludingOutsourcedEmployees");
  createBenchmark("Good: 40-55 | Warning: 35-40 or 55-59 | Action: < 35 or > 59", "expenseData", "row_personnelToCashExpenditure");
  createBenchmark("Good: < 15 | Warning: 15-19 | Action: > 19", "expenseData", "row_mandatoryDebtServiceToCashExpenditure");
  createBenchmark("Good: 40-55 | Warning: 35-40 or 55-59 | Action: < 35 or > 59", "expenseData", "row_personnelIncludingToTotalCashExpenditures");
  createBenchmark("Good: > 10 | Warning: 5-10 | Action: < 5", "expenseData", "row_totalGlobalAndLocalOutreachExpenses");
  createBenchmark("", "expenseData", "row_cashExpendituresPerGivingUnit");

  createWhatDoesThisMean(benefitsToSalaries_whatDoesThisMean, "row_benefitsToSalaries");
  createWhatDoesThisMean(benefitsSalariesTotal_whatDoesThisMean, "row_salariesBenefitsIncludingOutsourcedEmployees");
  createWhatDoesThisMean(personnelInclude_whatDoesThisMean, "row_personnelToCashExpenditure");
  createWhatDoesThisMean(mandatoryDebtService_whatDoesThisMean, "row_mandatoryDebtServiceToCashExpenditure");
  createWhatDoesThisMean(personnelInclude_whatDoesThisMean, "row_personnelIncludingToTotalCashExpenditures");
  createWhatDoesThisMean(totalCashExpendExcludePerGU_whatDoesThisMean, "row_cashExpendituresPerGivingUnit");

  // Removed facility expense and cost per square foot ratios per todo

  closeSidebarAfterSelectingOption("expense");
};
